### ISSUE TITLE
ModuleNotFoundError: No module named 'gimme_aws_creds'

### ISSUE THREAD

**Issue by vikten22** [Nike-Inc/gimme-aws-creds#100]
Error while executing "gimme-aws-creds" 

Traceback (most recent call last):
  File "/root/gimme-aws-creds-1.0.13/bin/gimme-aws-creds", line 13, in <module>
    from gimme_aws_creds.main import GimmeAWSCreds
ModuleNotFoundError: No module named 'gimme_aws_creds'

**Comment by Sector95** [comment]
This is almost always a Python environment issue.  Not knowing anything about the environment is going to make this difficult to diagnose.
