### ISSUE TITLE
Option to remember the Verify Factor

### ISSUE THREAD

**Issue by edubxb** [Nike-Inc/gimme-aws-creds#109]
According to the documentation:

https://developer.okta.com/docs/api/resources/authn#verify-factor

the **Verify Factor** factor can be remembered for a limited time by the server.

## Expected Behavior

Allow user to choose if want the **Verify Factor** be remembered.

## Context

When managing a lot of accounts with different roles, is a little pain to being prompted constantly for the second factor, so having the ability to remember it ease the workflow a lot.

**Comment by Sector95** [comment]
#110
