### ISSUE TITLE
gimme-aws-creds does not honor Nike OKTA App timeout

### ISSUE THREAD

**Issue by jaguth** [Nike-Inc/gimme-aws-creds#112]
## Expected Behavior
My OKTA app had an expiration of 1 hour.  I then went through the process to increase it to 4 hours.  Now when I login to my AWS web console through OKTA, my session doesn't expire for 4 hours.
However, when I run gimme-aws-creds and select the same OKTA app, the duration is still set to the default of 1 hour.  So, I run 'gimme-aws-creds --configure' and set the following:  'AWS Default Session Duration [3600]: 14400'.  14400 seconds = 4 hours.  And then i run gimme-aws-creds again and select my OKTA app, and it throws this error message:  "The requested session duration was too long for this role.  Falling back to 1 hour."
So, gimme-aws-creds is not honoring the OKTA app expiration.

## Current Behavior
Can only set session duration to 1 hour.  Setting to anything above 1 hour will cause it to throw the error "The requested session duration was too long for this role.  Falling back to 1 hour.".

## Possible Solution
gimme-aws-creds should honor the session duration in the OKTA app.

## Steps to Reproduce (for bugs)
Complete steps here:  https://confluence.nike.com/display/NSL/Requesting+4+hour+OKTA+timeout
Went through L1 and L2 levels to get specific AWS web console app expiration set to 4 hours.
Then tried authenticating with the app with gimme-aws-creds to get a 4-hour lease, but it fails with the error "The requested session duration was too long for this role.  Falling back to 1 hour.".

All details - such as application name and so on - can be found in the confluence link.  I do not want to expose any sensitive information in this issue request.

## Context
So this is for an aws test account.  When i develop in the test account, it is wasteful to have such a short timeout.  And when it happens, i must go through the whole gimme-aws-creds spiel just to continue.  And if i have some sort of service running locally, then i must kill it and restart it.  Every single hour.  And if we take into account the 15-minute developer randomization rule and getting pulled "out of the zone", I waste 15 minutes every hour just re-authenticating to AWS via cli.  That adds up to a lot of lost time and money for the company.  So I feel it makes sense to fix this issue to reduce developer friction.

## Your Environment
* App Version used:  gimme-aws-creds 1.1.4
* Environment name and version: bash
* Operating System and version: OSX Mojave 10.14.3

**Comment by Sector95** [comment]
@epierce I recall you running into something like this before with this project, any recollection?

**Comment by jaguth** [comment]
well, when i ran into the issue, i got the okta web console access updated to support a 4-hour lease.  after, i tried using gimme-aws-creds, and the reproduced issue i found is what i posted here.  i think this is the same thing.

**Comment by jaguth** [comment]
I think i found the issue.  The duration for a saml role is set in the "Maximum CLI/API session duration" field for the role.  So this does not seem to be a bug with gimme-aws-creds; its just that the okta web console authentication has different duration rules than the boto saml authentication duration.  the roles i'm using all have a max of 1 hour.  If i want to change that, then i would have to change it in the role itself.

**Comment by fantapop** [comment]
@jaguth is there a work around for this issue?
