### ISSUE TITLE
Support usage as a library [enhancement]

### ISSUE THREAD

**Issue by tmckay** [Nike-Inc/gimme-aws-creds#120]
gimme-aws-creds is a great CLI tool and it has some useful code that would be great to use as a library. Is there any plan to document / support usage as a library?

**Comment by nazarewk** [comment]
This module's code structure is 100% CLI usage minded, making it into library would require a rewrite in orders of 80% LoC.

Right now i am making it usable in scripting in #119 , this might help.

**Comment by Sector95** [comment]
The code base could really probably use a refactor anyway for whatever that's worth.  Always bugged me that the UI interaction wasn't centralized. :grimacing:

**Comment by Sector95** [comment]
Merged in #119
