### ISSUE TITLE
Version 1.1.8 not released on pypi

### ISSUE THREAD

**Issue by Firefishy** [Nike-Inc/gimme-aws-creds#123]
The [init.py version](https://github.com/Nike-Inc/gimme-aws-creds/blob/master/gimme_aws_creds/__init__.py#L2) was not updated for the last release, which likely resulted in the version on https://pypi.org/project/gimme-aws-creds/ not being updated.

**Comment by Firefishy** [comment]
It would be likely a good idea to update the `setup.py` to be more conventional and add the long description from `README.md`, per [example here](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py).

I'm happy to PR this change if desired.

**Comment by Sector95** [comment]
Appreciate the heads up, version bumped and v1.1.8 should be building now.

Would love a PR!  Thank you!

**Comment by Firefishy** [comment]
Closing this issue as resolved.
