### ISSUE TITLE
UnboundLocalError: local variable 'aws_creds' error

### ISSUE THREAD

**Issue by mikehalof** [Nike-Inc/gimme-aws-creds#131]
Hi,
I've installed latest and I'm using python 3.6.8 on CentOS 7. 
If I set AWS Role ARN to all, I'm receiving the below error

writing role arn:aws:iam::XXXXXXXXXX:role/YYYYYYYYYY to /home/centos/.aws/credentials
Traceback (most recent call last):
  File "/home/centos/environments/oktaaws/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/home/centos/environments/oktaaws/lib64/python3.6/site-packages/gimme_aws_creds/main.py", line 492, in run
    aws_creds['AccessKeyId'],
UnboundLocalError: local variable 'aws_creds' referenced before assignment
(oktaaws) [centos@ip-10-77-12-54 oktaaws]$

## Expected Behavior
Write aws credential to the /home/centos/.aws/credentials for all my roles
## Current Behavior
Giving me error

## Possible Solution
None

It's working fine if I leave AWS Role ARN blank. I can pick up a role from the list 

Halof

**Comment by mikehalof** [comment]
AWS IAM Role was bad, code didn't catch the AWS error code
I fixed the IAM Role and error got solved
Halof

**Comment by acabrera-rms** [comment]
Could you provide more details on what was wrong and how you fixed it please?

**Comment by mikehalof** [comment]
Hi,
nothing in the code. My AWS configuration was wrong and was generating an error
I just modify on AWS side.
halof
