### ISSUE TITLE
Google Authenticator. "Error: Invalid token provided"

### ISSUE THREAD

**Issue by elice02** [Nike-Inc/gimme-aws-creds#133]
I don't seem to be able to get Google authenticator to work with this tool. I register a device and then try and login and it states that the token is invalid, even though it is valid. 

Do you have any idea how to get this working, as I urgently need to derive AWS keys for authenticating.

```
kas@K:~$ gimme-aws-creds --profile esure --username kas@asdasd.com --register_device
Please enter password for encrypted keyring:
Using password from keyring for kas@asdasd.com
Multi-factor Authentication required.
token:software:totp( GOOGLE ) : kas@asdasd.com selected
Enter verification code: 906171
Device token saved!
kas@K:~$ gimme-aws-creds --profile esure --username kas@asdasd.com
Please enter password for encrypted keyring:
Using password from keyring for kas@asdasd.com
Multi-factor Authentication required.
token:software:totp( GOOGLE ) : kas@asdasd.com
Enter verification code: 040174
Error: Invalid token provided
```

**Comment by Sector95** [comment]
I'm having a hard time thinking of a way that gimme-aws-creds could be messing this one up, particularly since I know of a couple of users that have been using Google Authenticator with this.  Do we know for sure this isn't an MFA configuration issue in Okta?

**Comment by abhisoniks** [comment]
I am facing the same issue. 
```
(gimme-aws-creds) abhishek-mba:gimme-aws-creds abhishek$ gimme-aws-creds
Using password from keyring for abhishek
Password for abhishek:
Do you want to save this password in the keyring? (y/n) n
Multi-factor Authentication required.
Pick a factor:
[0] token:software:totp( GOOGLE ) : abhishek@qubole.com
Selection: 0
Enter verification code: 605889
Error: Invalid token provided
```

Does gimme-aws-creds support Google Authenticator?

**Comment by olearytd** [comment]
I get this same error on all Authentication methods using my Mac.

It works with the same token factor option on a centos 7 vm - anyone have this working on mac?

**Comment by olearytd** [comment]
RE: my specific issue was a config error

my config had
```
gimme_creds_server = app_url
```

where it needed to be
```
gimme_creds_server = appurl
```

**Comment by bwynsm** [comment]
Closing for now - I think this is an issue that has been addressed.
If found again, we can re-open.
