### ISSUE TITLE
exceeding the default duration of a role breaks

### ISSUE THREAD

**Issue by eedgar** [Nike-Inc/gimme-aws-creds#134]
set aws_default_duration to something larger than the iam roles duration and a traceback occurs

## Expected Behavior
no traceback

## Current Behavior
traceback and it fails
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/usr/local/lib/python3.7/site-packages/gimme_aws_creds/main.py", line 500, in run
    aws_creds['AccessKeyId'],
UnboundLocalError: local variable 'aws_creds' referenced before assignment

## Possible Solution
                if ex.response['Error']['Message'] == 'The requested DurationSeconds exceeds the MaxSessionDuration set for this role.':
                    print("The requested session duration was too long for this role.  Falling back to 1 hour.", file=sys.stderr)
                    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, 3600)
                if r''''durationSeconds' failed to satisfy constraint: Member must have value less than or equal''' in  ex.response['Error']['Message']:
                    print("The requested session duration was too long for this role.  Falling back to 1 hour.", file=sys.stderr)
                    aws_creds = self._get_sts_creds(aws_partition, saml_data['SAMLResponse'], role.idp, role.role, 3600)

**Comment by bwynsm** [comment]
I'm unable to replicate this now.
