### ISSUE TITLE
"Configuration file not found!" even when passing --action-configure

### ISSUE THREAD

**Issue by stevesta** [Nike-Inc/gimme-aws-creds#138]
```
root@b1f660e33c5c:/# gimme-aws-creds
Configuration file not found! Use the --action-configure flag to generate file.

root@b1f660e33c5c:/# gimme-aws-creds --action-configure
Configuration file not found! Use the --action-configure flag to generate file.
```

## Steps to Reproduce (for bugs)

I see this with gimme-aws-creds 2.0.0 Python 3.6.8 on ubuntu:latest docker image.

I also see this with Python 3.6.7 on mac osx.

**Comment by Sector95** [comment]
Interesting.  Do you get the same behavior with the `--configure` flag?

**Comment by foxxeehi** [comment]
Same issue here with Python 3.7.2 on windows 10.

**Comment by jpf** [comment]
I was able to get past this step by running `touch ~/.okta_aws_login_config`

**Comment by Sector95** [comment]
I swear we had addressed this issue in the past... I'll dive in real quick and see what's up.

**Comment by JoshCrosby** [comment]
I'm afraid I am still running into this issue on linux. 


```
$ docker version

Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Jul  1 18:51:44 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Jul  1 18:53:20 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
Running this produces the error, ~/.okta_aws_login_config exists and is empty.

```
$ gimme-aws-creds --action-configure --profile dev_life_it

Configuration profile not found! Use the --action-configure flag to generate the profile.```

**Comment by casey-robertson** [comment]
The usage of '~' isn't a best practice on Windows machines.  How does the code decide where to look for the configuration file?  We templated out configs for our devs so they only have to enter their Okta password but so far it's hit and miss whether the tool finds it.  Should we be setting the $OKTA_PROFILE environment variable?  Does that 'set' it so that it finds it on subsequent runs?  Conversely the tool works fine on my Mac and that envvar is not set at all.  Confused!

**Comment by Sector95** [comment]
I believe Python handles the expansion of the `~`, and as a result the config will be stored at `C:/Users/<username>/.okta_aws_login_config` directory.

Closing this issue because the initial issue was fixed.  @casey-robertson if the issue persists for you, please feel free to open another issue!

**Comment by Firefishy** [comment]
I've annoyingly had to workaround this issue for homebrew, by touching the config file: https://github.com/Homebrew/homebrew-core/pull/41900
