### ISSUE TITLE
Credentials written to .aws\credentials do not work with AWS non-default regions

### ISSUE THREAD

**Issue by ian-barlow** [Nike-Inc/gimme-aws-creds#141]
The temporary credentials written to .aws\credentials work as expected with the default set of AWS regions (all except 'ap-east-1' and 'me-south-1') but cannot be validated in these two regions.

After the STS endpoint is enabled in the IAM account_settings (https://console.aws.amazon.com/iam/home?#/account_settings) and the region is enabled under the account (https://console.aws.amazon.com/billing/home?#/account) the credentials written to the file should 'work' in the newly enabled regions.

## Expected Behavior
`  PS> Get-STSCallerIdentity -ProfileName [SomeProfile] -region ap-east-1 | fl`

Should return:
```LoggedAt         : 14-Oct-19 2:51:22 PM
Account          : 123456789012
Arn              : arn:aws:sts::123456789012:assumed-role/[RoleName]/[OktaIdentity]
UserId           : XXXXXXXXXXXXM2JDA2AVQ:[OktaIdentity]
ResponseMetadata : Amazon.Runtime.ResponseMetadata
ContentLength    : 495
HttpStatusCode   : OK
```

## Current Behavior
```
PS> Get-STSCallerIdentity -ProfileName [SomeProfile] -region ap-east-1 | fl
Get-STSCallerIdentity : The security token included in the request is invalid
At line:1 char:1
+ Get-STSCallerIdentity -ProfileName [SomeProfile] -region ap-east-1 | fl
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Amazon.PowerShell.C\u2026allerIdentityCmdlet:GetSTSCallerIdentityCmdlet) [Get-STSCallerIdentity], InvalidOperationException
+ FullyQualifiedErrorId : Amazon.SecurityToken.AmazonSecurityTokenServiceException,Amazon.PowerShell.Cmdlets.STS.GetSTSCallerIdentityCmdlet
```
Same (problematic) behavior seen when using AWS CLI Tools. Using debug on CLI tools show the API call failing to authenticate when sent to STS endpoint in non-default region.

## Steps to Reproduce (for bugs)

1. Collect a set of credentials with aws-gimme-creds 
2. Specify a non-default region on an AWS command line

## Context
Script to setup an AWS environment fails when targeted non-default region

## Your Environment

* App Version used: latest (2.0.1)
* Environment name and version: 
* Operating System and version: Windows 10 / Python 3.7.3

**Comment by Sector95** [comment]
I'm not seeing this behavior-- Just pulled down a credential in `us-west-2`, then executed `aws sts get-caller-identity --region us-east-1` and I was able to get my user info back.

**Comment by nmaclennan-chwy** [comment]
Do you have those regions [enabled in your accounts](https://docs.aws.amazon.com/general/latest/gr/rande-manage.html#rande-manage-enable)? I think they're not enabled by default.

**Comment by ian-barlow** [comment]
> I'm not seeing this behavior--
> Just pulled down a credential in `us-west-2`, then executed `aws sts get-caller-identity --region us-east-1` and I was able to get my user info back.
You're looking at original, not the new regions ('ap-east-1' and 'me-south-1') which we are having issues with, the symptoms being observed are only in relation to these regions which are fully enabled in our accounts as already noted in the problem report.

**Comment by Sector95** [comment]
I see, I'm not sure how this could be an issue with gimme-aws-creds though, as we simply leverage the AWS endpoints to get the credentials.  This feels more like an AWS idiosyncrasy to me.  Perhaps those new regions are not yet able to validate tokens from other regions?

**Comment by mhemani-fuze** [comment]
@Sector95 would it be possible to have gimme-aws-creds to retrieve temporary credentials from a particular regional STS endpoint rather than the global one? By default, global credentials issued from the global endpoint (https://sts.amazonaws.com) are only valid in the "Default" regions, but if issued from any regional endpoint (https://sts.us-east-2.amazonaws.com), then they would be valid in the opt-in regions like ap-east-1 and me-south-1.

**Comment by reegnz** [comment]
Ooookay, I managed to figure out a reasonable solution.

Just setting AWS_DEFAULT_REGION to any region should work fine.

Eg.:
```sh
AWS_DEFAULT_REGION=us-east-1 gimme-aws-creds
```
I've inspected it with mitmproxy and the SDK goes to a regional STS endpoint if that variable is defined.
