### ISSUE TITLE
Config File default location - Windows

### ISSUE THREAD

**Issue by casey-robertson** [Nike-Inc/gimme-aws-creds#142]
## Expected Behavior
Create a config file in C:\Users\username.  Expect upon running `gimme-aws-creds` that it will leverage the file.  

## Current Behavior
On a Mac, no problem.  Create the file in `~`, app picks it up.  On Windows it seems hit and miss and I'm unable to determine what location the file should be in.  

## Steps to Reproduce (for bugs)
1.  Create an .okta_aws_login_config file in C:\Users\username
2. Run `gimme-aws-creds`
3.  User prompted to run config wizard despite file being there

## Context
Trying to automate onboarding for developers.  Scripting is working well for Mac but Windows has been problematic.  I realize now there is an environment variable called $OKTA_CONFIG referenced.  This seemed promising until I realized this envvar is not set on my Mac yet I'm able to rum the `gimme-aws-creds` from any working directory and it finds my config file in `~`

## Your Environment
Mixed Macs and PCs - all Windows 10.  Python 3.7.x on clean installs....varies on existing machines.

**Comment by casey-robertson** [comment]
Dropped the file in C: and in the %USERPROFILE% directory.  Still not picking it up on a clean Windows 10 vagrant box.  So I ran through the wizard.... login works.  But no file .okta_aws_login_config anywhere to be found.  Where is it storing this???

**Comment by Sector95** [comment]
The file is hidden by default in Windows because it starts with a `.`.  The full path should be:
`C:\Users\<username>\.okta_aws_login_config`
