### ISSUE TITLE
MacOs:Catalina - gimme-awscreds is creating a ~ directory at home directory, wasn't present in Mojave

### ISSUE THREAD

**Issue by j0nathontayl0r** [Nike-Inc/gimme-aws-creds#146]
## Expected Behavior
gimme-aws-creds should be writing AWS keys to a users homedirectory at:

```~/.aws/credentials```

## Current Behavior

gimme-aws-creds is creating a directory named ~ at your homedirectory like is shown below:

```/Users/username/~.aws/credentials/```

## Possible Solution
I'm manually setting the following variable to my hardcoded user path:

AWS_SHARED_CREDENTIALS_FILE=/Users/jonathontaylor/.aws/credentials

I'd guess this problem is more likely to be a possible with Python3 and Catalina than a problem with your package specifically. I think it's how Python 3 is now handling FILE_ROOT, found in Line 107 main.py:

```
        self.ui = ui
        self.FILE_ROOT = self.ui.HOME
        self.AWS_CONFIG = self.ui.environ.get(
            'AWS_SHARED_CREDENTIALS_FILE',
            os.path.join(self.FILE_ROOT, '.aws', 'credentials')
```

## Steps to Reproduce (for bugs)

0. Make the mistake of installing MacOS Catalina
1. run gimme-aws-creds --profile AWSProfileName
2. gimme-aws-creds creates the following path /Users/username/~./aws/credentials
3. Spend a day trying to figure out why gimme-aws-creds isn't writing your credentials to file
4. ???
5. profit

## Context
I'm trying to run gimme-aws-creds to write my newly generated keys to my .aws/credentials key file. 

## Your Environment
MacOS Catalina sucks. AWS CLI and pip3 are up to date.

**Comment by Sector95** [comment]
Ooph, that's a fun one.  I'm going to have a hard time testing this myself, let me see if I can find a cohort that has Catalina.

**Comment by JDTAY** [comment]
@Sector95. I'll try this again myself on a clean device and get back to you.

**Comment by pab1it0** [comment]
Current WA is to create an empty credentials file.

**Comment by JDTAY** [comment]
Is that to say you had this same problem @pab1it0 ?
I've performed a clean install of Catalina on my Mac and I've not experienced this issue again.

**Comment by JDTAY** [comment]
@pab1it0 not related to this at all but cloud-wards is being index on DuckDuckGo via IP now by your FQDN.

Searching for cloud-wards or your name in DuckDuckGo returns the below on the second result.
https://18.197.107.125/author/user/
