### ISSUE TITLE
Readme file gives poor guidance.

### ISSUE THREAD

**Issue by zerolaser** [Nike-Inc/gimme-aws-creds#147]
The **README** file doesn't explain where to get client_id and gimme_creds_server url.

**Comment by Sector95** [comment]
We can't necessarily tell you exactly where to get it, as it's going to differ per your organization.  The client_id and gimme_creds_url are going to depend on how your group deploys the server Lambda.

**Comment by zerolaser** [comment]
Ok. I understand that. Why isn't there a repo for setting up gimme-aws-creds server or documentation?

**Comment by Sector95** [comment]
https://github.com/Nike-Inc/gimme-aws-creds/blob/master/lambda/

**Comment by frankscalzo** [comment]
I am new at lambda and trying to deploy this is the Okta API key the same as the API Token since my company does not pay for the API server service i don't have that tab in Okta
