### ISSUE TITLE
OKTA_API_KEY is an environment variable that cannot be set

### ISSUE THREAD

**Issue by ChrisDilts** [Nike-Inc/gimme-aws-creds#149]
## Expected Behavior
Per README, the OKTA_API_KEY is an environment variable that needs to be set.

## Current Behavior
OKTA_API_KEY='<api key>' is not one of the env variables that can be set, such as AWS_DEFAULT_DURATION, OKTA_MFA_CODE 

## Possible Solution
Allow this env variable to be added to the .okta_aws_login_config file and used during login.

## Steps to Reproduce (for bugs)
1. Command: gimme-aws-creds --config
2. Enter 'internal' for gimme-creds-server
3. Complete the remaining config
4. Command: gimme-aws-creds
5. Observe console output "OKTA_API_KEY environment variable not set!"

## Context
This issue prevents request and reception of temp AWS tokens.

## Your Environment

* App Version used: 2.0.2
* Environment name and version: 
* Operating System and version: Win10Pro 1709

**Comment by vennemp** [comment]
Running on a windows system.  I have an Okta API Key, I even added it to config file for a new entry OKTA_API_KEY.. nothing..  Does it even look like the package is written properly as it throws an additional error..

C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gimme_aws_creds-2.1.0-py3.8.egg\gimme_aws_creds\okta.py:664: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\USER\AppData\Local\Programs\Python\Python38-32\lib\site-packages\gimme_aws_creds-2.1.0-py3.8.egg\gimme_aws_creds\okta.py:664: SyntaxWarning: "is not" with a literal. Did you mean "!="?
OKTA_API_KEY environment variable not found!

**Comment by epierce** [comment]
`OKTA_API_KEY` is read by gimme-aws-creds - If you're still having an issue with this, let me know

**Comment by mlopez-eb** [comment]
@epierce this is still an issue for me. brew installed and went through the configuration setup. at the end when trying to run it, we get that error 

```OKTA_API_KEY environment variable not found!```

**Comment by fpereyrap** [comment]
hello, having isssues with this even when using internal.
