### ISSUE TITLE
Application Prompts for MFA Twice

### ISSUE THREAD

**Issue by russellgarrisonaver** [Nike-Inc/gimme-aws-creds#150]
## Expected Behavior

We would expect to only get prompted once for MFA to get AWS credentials each time we run gimme-aws-creds to obtain temporary credentials.

## Current Behavior

We have a few Okta applications that require MFA for every sign on using a Sign On Policy in Okta. Those applications cause gimme-aws-creds to prompt for MFA twice, while others without the policy only prompt once. We can even suspend the policy rule for an application in Okta to control the behavior in gimme-aws-creds.

## Possible Solution

Pasting the app URL into a browser does not result in getting prompted for MFA twice, so it seems like there may be a way to support applications with a sign on policy that requires MFA each time.
## Steps to Reproduce (for bugs)

1. Apply a sign on policy to the Okta AWS App that requires MFA every sign on.
2. Run gimme-aws-creds against that application.
3. Get prompted for MFA twice.
4. Disable the sign on policy rule in Okta and test again.

## Context

This is more an inconvenience than anything else, but it is different than the IAM-based experience we are replacing. Users not employing push will have to wait for a new code to generate making the whole process seem to drag.

## Your Environment

* App Version used: 2.1.0
* Environment name and version: Python 2.7.16
* Operating System and version: macOS 10.14.6

**Comment by mikehalof** [comment]
I'm experiencing the same /(annoying) behavior. 
MH

**Comment by Sector95** [comment]
We had a bug in our MFA selection code that _might_ have been causing this.  I noticed after upgrading to 2.1.3 I didn't get prompted again.

Can you guys upgrade, make sure you have `remember_device` set to `True` in your configs, and give it another shot and let me know how it works for ya?

**Comment by mikehalof** [comment]
Hi,
I'm still experiencing the same.

.......

(fscaws) [centos@ip-10-77-6-142 ~]$ gimme-aws-creds
Okta Password for 105710986:
Multi-factor Authentication required.
Okta Verify App: SmartPhone_IPhone: Michele’s iPhone selected
Okta Verify push sent...
Multi-factor Authentication required.
Okta Verify App: SmartPhone_IPhone: Michele’s iPhone selected
Okta Verify push sent...
Pick a roles:
....
cat .okta_aws_login_config

resolve_aws_alias = True
preferred_mfa_type = push
remember_device = True
....

MH

**Comment by epierce** [comment]
How do you have the org-level policy that requires MFA configured?  Do you require MFA on every sign-on at that level or is just on new devices?

**Comment by mikehalof** [comment]
I do have 2FA for Okta AWS application on every sign-on, valid for 1h session (same as AWS console).
MH

**Comment by epierce** [comment]
In addition to the app-level policy for the AWS app, you must also have a org-level policy (i.e. when you access the Okta dashboard) that requires MFA.  What's the frequency required for MFA on that policy?

**Comment by mikehalof** [comment]
Okta Dashboard (home page) doesn't require MFA for my company. 2FA comes for certain apps inside the dashboard only. AWS Console is one of them
MH

**Comment by epierce** [comment]
Is your user account an Okta admin? The initial MFA challenge has got to be coming from the call to the Auth API and the only ways I can think of to fire an MFA challenges from there is an org-level sign-on policy or the new "require MFA for all admins" feature.  When using a browser, that doesn't require the second factor until you click on the "admin" button in the OKta dashboard, but it's required immediately when using the Auth API.

**Comment by mikehalof** [comment]
Hi, as far as I know, I'm not an admin. I'll double check with Okta support team
Thanks
MH

**Comment by zswanson** [comment]
Hi following up on this issue, we're just transitioning to gimme-aws-creds from okta-aws (which is now abandoned) and we're seeing the repeated MFA prompts. In this case I can confirm that yes, our users experiencing this ARE okta Admins/SuperAdmins.

**Comment by Sector95** [comment]
Turns out that the inconsistency people were facing in regards to this bug was caused by a very small difference in people's config files:

`okta_org_url = https://company.okta.com`
vs
`okta_org_url = https://company.okta.com/`

v2.3.3 is building as we speak, if you guys could test it our and report back, that'd be great!  Will hopefully be able to close out this issue.

**Comment by samgurtman** [comment]
Still being asked for MFA twice with 2.3.3. Maybe it's a different issue though? 

What we see is that it actually fails if you use the same code twice. To get it to work you have to wait for the TOTP code to rollover between the first and second prompts.

**Comment by Sector95** [comment]
Can you confirm that the `device_token` parameter in your config is populated with a value, and `remember_device` is set to `True`?

**Comment by russellgarrisonaver** [comment]
I updated just now, but it is still happening.

--------------------


$ gimme-aws-creds
Using password from keyring for russ
Okta Password for russ: 
Do you want to save this password in the keyring? (y/n) n
Multi-factor Authentication required.
Pick a factor:
[0] token:software:totp( GOOGLE ) : russ
[1] sms: +1 XXX-XXX-1212
[2] webauthn: webauthn
[3] webauthn: webauthn
[4] Okta Verify App: Lumia 928
[5] token:software:totp( OKTA ) : russ
Selection: 0
Enter verification code: 123456
Multi-factor Authentication required.
Pick a factor:
[0] token:software:totp( GOOGLE ) : russ
[1] webauthn: webauthn
[2] webauthn: webauthn
[3] Okta Verify App: Lumia 928
[4] token:software:totp( OKTA ) : russ
Selection: 0
Enter verification code: 654321
Pick a roles:
Account: contoso (123456789012)
      [ 0 ]: role0
      [ 1 ]: role1
      [ 2 ]: role3
      [ 3 ]: role4
Selections (comma separated): 1
Saving arn:aws:iam::123456789012:role/role1 as role1
Written profile role1 to /Users/russ/.aws/credentials
$ 


[DEFAULT]
okta_org_url = https://contoso.okta.com
okta_auth_server =
client_id =
gimme_creds_server = appurl
aws_appname =
aws_rolename =
write_aws_creds = True
cred_profile = role
okta_username = russ
app_url = https://contoso.okta.com/home/amazon_aws/5ezeau1x7h00ng3yld63/129
resolve_aws_alias = True
preferred_mfa_type = 
remember_device = True
aws_default_duration = 3600
device_token =
output_format = export

**Comment by Sector95** [comment]
Your `device_token` config parameter is empty, try running `gimme-aws-creds --register_device`.

**Comment by russellgarrisonaver** [comment]
Thanks that worked! I don't seem any info on what that parameter does. What is it?

**Comment by Sector95** [comment]
I was noticing the same, not sure where the documentation on that flag went.  Further, I think the registration was supposed to happen automatically, not sure why it's not for some people.

Basically it takes the device ID from the Okta response, and stores it in the cookie for future requests, that way Okta doesn't keep prompting for MFA from devices it's already authorized recently.

**Comment by z0ph** [comment]
Worked for me, thanks (`gimme-aws-creds --register_device`)

**Comment by cturner-confluent** [comment]
Sorry to dig up old bones here, but does anyone here know how long that device_token should last? Is it forever, until your next OKTA Password Reset, etc.? Any ideas, I can't see to find this in the OKTA docs?

**Comment by russellgarrisonaver** [comment]
I don't know if there is an expiration, but I haven't had to change it since I set it. My password has had to change several times since then, but the token is the same.
