### ISSUE TITLE
gimme-aws-creds now available in homebrew

### ISSUE THREAD

**Issue by Firefishy** [Nike-Inc/gimme-aws-creds#153]
FYI...

If running OSX with Homebrew, gimme-aws-creds can now be installed by running:

```
brew install gimme-aws-creds
```

When I get a chance I will PR an install documentation change for this.

**Comment by Firefishy** [comment]
PR for adding to homebrew: https://github.com/Homebrew/homebrew-core/pull/41900

**Comment by Sector95** [comment]
Very cool, thanks!  I can't tell from that thread, but does Homebrew need to be updated to new versions manually, or does it pick up on new versions from PyPi?

**Comment by Firefishy** [comment]
@Sector95 Manual PR with updated version. Update PRs are normally accept quickly.
Only these 2 lines need to be changed in the PR: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gimme-aws-creds.rb#L6-L7

**Comment by Firefishy** [comment]
FYI...
https://github.com/Homebrew/homebrew-core/pull/47376
https://github.com/Homebrew/homebrew-core/pull/47508
