### ISSUE TITLE
FIDO2 breaking change

### ISSUE THREAD

**Issue by szechyjs** [Nike-Inc/gimme-aws-creds#155]
The latest version of the fido2 library changes the `get_assertion` function which breaks MFA.

https://github.com/Yubico/python-fido2/releases/tag/0.8.1

## Expected Behavior
webauthn/U2F tokens should work

## Current Behavior
`TypeError: get_assertion() takes 2 positional arguments but 4 were given`

## Possible Solution
Update the code to work with latest version of python-fido2, or lock to `fido2==0.7.3`

## Steps to Reproduce (for bugs)

1. Use webauthn MFA

## Your Environment
* App Version used: 2.1.3
* Environment name and version: Python 3.7.3
* Operating System and version: macOS 10.14.6

**Comment by Sector95** [comment]
Breaking change in a minor release, eh?  Bad fido, bad.

We'll lock it for now.

**Comment by Sector95** [comment]
Added to release 2.2.0.  Thanks!
