### ISSUE TITLE
Duo MFA fails to load web page for iframe and gives syntax error

### ISSUE THREAD

**Issue by confusedcrib1** [Nike-Inc/gimme-aws-creds#159]
## Expected Behavior

Choosing Duo web as MFA should open a webpage which opens the iframe for sending a push notification for authentication.

## Current Behavior
A browser opens to http://127.0.0.1:65432/duo.html with a failure to connect, and the below is returned (powershell):

Pick a factor:
[0] web: Duo
Selection: 0
Duo required; opening browser...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 262, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\runpy.py", line 237, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\Scripts\gimme-aws-creds.cmd", line 1
    @echo OFF
          ^
SyntaxError: invalid syntax

**Comment by seb-steuer** [comment]
Correct that doesnt work.
But I thought the DUO support implements the browserless feature from okta keyman and you can get duo push to your phone without any need of a browser.

That doesnt appear to be an option for me unfortunately:

`$ gimme-aws-creds
Using password from keyring for XXX
Okta Password for XXX:
Do you want to save this password in the keyring? (y/n) n
Multi-factor Authentication required.
Pick a factor:
[0] web: Duo
Selection: 0
Duo required; opening browser...`

I've tried different values for preferred_mfa_type but no success

**Comment by Sector95** [comment]
Could this be related to #168 ?

**Comment by elijah-roberts** [comment]
> Could this be related to #168 ?

@Sector95  looks like dynamic ports was release in 2.3.1. Just tested in 2.3.0 and am getting the same issue.

python 3.8.2

[Uploading image.png…]()


![image](https://user-images.githubusercontent.com/19742213/78079440-5ac76a00-7369-11ea-9223-416365bfad8a.png)

**Comment by elijah-roberts** [comment]
@Sector95 @confusedcrib1 
I think the issue must be with the https://github.com/Nike-Inc/gimme-aws-creds/blob/master/bin/gimme-aws-creds.cmd.

I am able to successfully run by explicitly running `python /path/to/gimme-aws-creds/python/script


This specifically seems to be an issue when a new process is called, like when spinning up a local duo server: https://github.com/Nike-Inc/gimme-aws-creds/blob/1c8461446b622fc50e209b54c5fdba2d66a5da5f/gimme_aws_creds/okta.py#L477

**Comment by tomamoto** [comment]
> @Sector95 @confusedcrib1
> I think the issue must be with the https://github.com/Nike-Inc/gimme-aws-creds/blob/master/bin/gimme-aws-creds.cmd.
> 
> I am able to successfully run by explicitly running `python /path/to/gimme-aws-creds/python/script
> 
> This specifically seems to be an issue when a new process is called, like when spinning up a local duo server:
> 
> https://github.com/Nike-Inc/gimme-aws-creds/blob/1c8461446b622fc50e209b54c5fdba2d66a5da5f/gimme_aws_creds/okta.py#L477
> 
> Which I am assuming re-calls the gimme-aws-creds.cmd and fails on the `@echo OFF` statement

Confirmed Elijah's workaround.  Don't have a real solution to contribute to the code at the moment, but you could just add shortcut to your path that runs something along the lines of `python.exe "C:\program files\Python36\Scripts\gimme-aws-creds"` (that path will vary based on how you've installed python on windows to begin with) and you're back up and limping along with your very own STS creds.

**Comment by elijah-roberts** [comment]
Digging in a little more it there definitely are some differences in python multiprocessing on unix systems vs windows: http://perfspy.blogspot.com/2017/05/python-multiprocessing-behaves.html

The most notable is:

> This difference is because on Linux, multiprocesses uses fork() to start a child-process, which inherits the memory status of the parent process. On Windows, there is no fork(), so a child-process starts running from scratch. 

As I understand it, this means that on windows rather than forking the process and inheriting the parent process's memory, it calls the same script again. In the case of this utility the activation script is a .cmd file which does not conform to to python syntax. 

From what I can tell the only part of this utility that uses multi-processing is the duo webserver functionality. So only windows users that are using duo will be affected. I have not done much window's python programming, and have not dealt with multi-processing on windows before, but looks pretty certain that it is a clashing between the mulitprocessing module, and python being run from inside another program (as running the script with just python works.)
