### ISSUE TITLE
need help understanding API / Lambda 

### ISSUE THREAD

**Issue by frankscalzo** [Nike-Inc/gimme-aws-creds#164]
trying to read the doc i am not seeing anything regarding servers under API i see i can make a token but thats all.

after contacting Okta they said i am not licensed for it i can make the token.

is this the same as Okta Key of do i have to have API server license to enable this.

sorry i know this is not a bug but needed help understand since i am not a Lambda person at all and when i thought i made the lambda i cant find the  following info

okta_auth_server  
client_id 
URL for gimme-creds-lambda

**Comment by epierce** [comment]
The lambda is optional.  You can save a read-only admin token in the `OKTA_API_KEY` environment variable and set `gimme_creds_server = internal` in your config file.  gimme-aws-creds will interact directly with your Okta domain and the lambda is not needed.

**Comment by dhess** [comment]
Hi, I have a related question. I'm an `aws-okta` refugee and I'm evaluating `gimme-aws-creds` as a potential replacement. Why is the Okta API key necessary for `gimme-aws-creds`? Neither `aws-okta` nor `saml2aws` needs one to authenticate with Okta in order to generate temporary AWS credentials.

**Comment by Sector95** [comment]
gimme-aws-creds queries Okta to generate a list of AWS applications that are relevant to the user.  I believe you can avoid the use of an API key entirely if you explicitly configure your gimme-aws-creds to use a specific ARN and Okta application ID.

**Comment by dhess** [comment]
@Sector95 Thanks, using an ARN and an Okta app-specific SAML URL is what we do for `aws-okta` (we use a hub-and-spoke model with AssumeRole), so hopefully that will work for us with `gimme-aws-creds`, as well. I'll follow up here when I've had a chance to try it out.

**Comment by jseiser** [comment]
> 



> gimme-aws-creds queries Okta to generate a list of AWS applications that are relevant to the user. I believe you can avoid the use of an API key entirely if you explicitly configure your gimme-aws-creds to use a specific ARN and Okta application ID.

Is there any documentation on this?  Our security team is never going to share a read only API key with everyone.  I tried doing waht you said, but it fails to connect.

```
❯ cat .okta_aws_login_config
[admin]
okta_org_url = https://auth.url.com <-- my real okta URL
okta_auth_server =
client_id =
gimme_creds_server = internal
aws_appname = AWS - Account <-- This is the app name in Okta
aws_rolename = arn:aws-us-gov:iam::account:role/okta_admin <-- this is a real ARN
write_aws_creds = True
cred_profile = role
okta_username = justin
app_url = https://auth.url.com/home/amazon_aws/fs90kfgkdfg9dfk/272 <-- the APP URL from Okta
resolve_aws_alias = False
include_path = False
preferred_mfa_type = token:hardware
remember_device = False
aws_default_duration = 3600
device_token =
output_format =
```


```
❯ gimme-aws-creds --profile admin
OKTA_API_KEY environment variable not found!
```
