### ISSUE TITLE
Would you accept a pull request to make use of the os' keyring optional?

### ISSUE THREAD

**Issue by aver-stephen-smith** [Nike-Inc/gimme-aws-creds#179]
Hello. We are finding that users sometimes save a bad password to the keyring and get confused. Would you be interested in a pull request to make interacting with the os' keyring configurable? We would probably disable the keyring to avoid confusion among our user base.

**Comment by Sector95** [comment]
I think I would rather see us improve the logic around login failures, like being prompted for a password after login failure with a keyring password vs. the whole execution failing.
