### ISSUE TITLE
Breaks for multi-aws-account single okta application setup.

### ISSUE THREAD

**Issue by onetinov** [Nike-Inc/gimme-aws-creds#18]
# Problem Statement
## Overview
The Okta setup documentation now has guidance on how to configure a single Okta application to refer to multiple downstream AWS accounts (http://saml-doc.okta.com/SAML_Docs/How-to-Configure-SAML-2.0-for-Amazon-Web-Service#scenarioB).  This breaks the cli / api assumptions made in gimme-aws-creds in 2 key areas - the role name and the identityProviderArn.  I am trying to work out how to best implement a fix. 

## Incorrect role name
First a quick example - 

```
[root@fe1728b00c12 okta-src]# gimme-aws-creds -u foo@bar.com
Password for foo@bar.com:
Authentication Success! Getting AWS Accountsdone

Pick an app:
[ 0 ] FOOBAR AWS Accounts
Selection: 0
Pick a role:
[ 0 ] [foobarcontractors] -- okta-xonk-admin
[ 1 ] [foobar-it] -- okta-it-admin
Selection: 0
Traceback (most recent call last):
<snip>
  File "/usr/lib/python3.4/site-packages/botocore/client.py", line 599, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the AssumeRoleWithSAML operation: Request ARN is invalid
```
Note that [foobarcontractors] and [foobar-it] are independent aws accounts with separate account ids.  These are not 2 roles within a single AWS account, rather they are 2 accounts with 1 saml role each.

I added a quick debug print to see what we are getting during the `_get_sts_creds` function -

```
print("Attempting STS with Role={}, Principal={}, Duration={}".format(self.role_arn,self.idp_arn,duration))
``` 
yields
```
Attempting STS with Role=arn:aws:iam::130894992587:role/[foobarcontractors] -- okta-xonk-admin, Principal=arn:aws:iam::123456789012:saml-provider/Okta, Duration=3600
```
Clearly this is broken due to the account string prefix.  So a quick and dirty fix would be a simple `re.sub` to kill the `[foobarcontractors] -- ` prefix before calling the role.  This leads to the next issue -

## Incorrect AWS Account ID
This one is a bit more thorny and will require some more digging.  In `_get_aws_account_info` we enumerate the API call - `{{url}}/api/v1/apps?filter=user.id+eq+"##USERID##"&expand=user/##USERID##`.  Inside the returned json, there is a single value for `final_result[0]['settings']['app']['identityProviderArn']` = `arn:aws:iam::123456789012:saml-provider/[Userdefinedstring]`.  Sadly this is AWS account id specific.  As such, even if we correctly regex sub the role-name above, the identityProviderArn will have the incorrect account id and the derived role arn account number will be incorrect and the SAML assertion will fail.  So we need to find some other way to infer aws account id.

If we just use the Okta website we can see the AWS account ids (note I had to censor the details of account numbers, hopefully doesn't affect clarity) - 

![okta saml](https://user-images.githubusercontent.com/4967942/31673145-774b6938-b32c-11e7-8088-68ff504dbb1a.JPG)

However, these account ID values don't exist in any of the datastructures we have in gimme-aws-creds currently.

---

## Possible solutions
So, for the AWS Account ids I have a range of options:

### Role name hints
To prefix this, I hate this idea, but through documentation you could require that users provide the target AWS account ID somewhere within the role name string.  i.e. `[foobar-it] -- okta-it-admin` becomes `[foobar-it] -- 123456789012-okta-it-admin`.  We could use this hint to locate aws account id if found.

### Give up on multi-account and just document the limitation
I am actually kind of ok on this, but it is a bit unsatisfying.  It is a similar amount of work to create a new Okta application as it is to tie multiple AWS accounts under a single application.  As such we could just document the limitation and require single AWS accounts under each Okta application, with as many roles for that account as you like.  We then will have the correct identity provider in the `final_result` for each application.

### Option X
So for this, we would need to go digging.  I don't know where to find the account number information displayed on the graphical saml page - but it has to be somewhere.  I think based on the successful auth we should be able to curl and parse the saml page to get the roles and account ids for example.

Any thoughts on the above, and relative interest in making the script work vs just documenting lack of support for multi-account setups?

**Comment by onetinov** [comment]
In terms of *Option X* - quick dirty diff on `gimme_aws_creds/okta.py`

```
+import base64
+import xml.etree.ElementTree as ET

    def get_saml_response(self, url):
<snip>
         for inputtag in saml_soup.find_all('input'):
             if inputtag.get('name') == 'SAMLResponse':
                 saml_response = inputtag.get('value')
+                role_pairs = []
+                root = ET.fromstring(base64.b64decode(saml_response))
+                for saml2_attribute in root.iter('{urn:oasis:names:tc:SAML:2.0:assertion}Attribute'):
+                    if (saml2_attribute.get('Name') == 'https://aws.amazon.com/SAML/Attributes/Role'):
+                        for saml2_attribute_value in saml2_attribute.iter('{urn:oasis:names:tc:SAML:2.0:assertion}AttributeValue'):
+                            role_pairs.append(saml2_attribute_value.text)
+                print (role_pairs)
```
yields - 

```
role_pairs = 
['arn:aws:iam::20<SNIP>68:saml-provider/Okta,arn:aws:iam::20<SNIP>68:role/okta-<SNIP>in', 
'arn:aws:iam::92<SNIP>22:saml-provider/Okta,arn:aws:iam::92<SNIP>22:role/okta-<SNIP>in', 
'arn:aws:iam::13<SNIP>87:saml-provider/Okta,arn:aws:iam::13<SNIP>87:role/okta-<SNIP>in']
```

So we definitely have the data.  Just need to work out how to key our identity provider and role based on the saml assertion from beautiful soup and not make assumptions based on the Okta api return.

**Comment by anners** [comment]
Hi @onetinov - We currently create one Okta app per AWS account, so we have not run into your particular use case but we do want to support it.  We are reviewing the possible options, thanks for your suggestions. Feel free to submit a PR if you get something working.

**Comment by onetinov** [comment]
Ok - I took a stab at it.  Let me know what you think - https://github.com/Nike-Inc/gimme-aws-creds/pull/19

**Comment by onetinov** [comment]
Incorporated the feedback, let me know if you think we should do more.  I believe this addresses the issue at hand, but as a new/separate topic, it now has me really wanting to eliminate the API key requirement entirely - it feels a bit icky to me to have to give my users an API key to stash in their environment and if it could just be based on their username/password I would be happier.

However, that almost feels like a real fork, although I hate to duplicate code - especially now this is working so well.  Maybe if we provided a config option to hard code the org_url and the app_url, we would no longer need the api_key enumeration of a user's SAML destinations.

Anyway, let me know what you think!

**Comment by SectorNine50** [comment]
We felt the same way, and actually ended up building a server component for this that handles all the Okta API calls.  I think was on it's way to becoming open source, but I'm not sure if that's still the case.

Being able to hard-code the URLs in the config is a really good way to go about this for those not wanting to leverage the server component, great idea.  We should add that to our list.

**Comment by SectorNine50** [comment]
Changes merged, thanks!  Feel free to open an issue regarding the replacement of the API key envar.
