### ISSUE TITLE
Installation fails on Windows 10

### ISSUE THREAD

**Issue by evgenii-brovkin** [Nike-Inc/gimme-aws-creds#190]
When trying to install the app following error occurs:

Collecting fido2<=0.7.3,>=0.7.0
  Using cached fido2-0.7.3.tar.gz (188 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\EBrovk\Miniconda3\envs\corona\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\EBrovk\\AppData\\Local\\Temp\\1\\pip-install-6zudh3oy\\fido2\\setup.py'"'"'; __file__='"'"'C:\\Users\\EBrovk\\AppData\\Local\\Temp\\1\\pip-install-6zudh3oy\\fido2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\EBrovk\AppData\Local\Temp\1\pip-install-6zudh3oy\fido2\pip-egg-info'
         cwd: C:\Users\EBrovk\AppData\Local\Temp\1\pip-install-6zudh3oy\fido2\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\EBrovk\AppData\Local\Temp\1\pip-install-6zudh3oy\fido2\setup.py", line 33, in <module>
        if StrictVersion(__version__) < StrictVersion("20.2"):
      File "C:\Users\EBrovk\Miniconda3\envs\corona\lib\distutils\version.py", line 40, in __init__
        self.parse(vstring)
      File "C:\Users\EBrovk\Miniconda3\envs\corona\lib\distutils\version.py", line 137, in parse
        raise ValueError("invalid version number '%s'" % vstring)
    ValueError: invalid version number '46.1.3.post20200330'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

## Expected Behavior

Successful installation

## Current Behavior

An error
## Possible Solution

The cause of the problem is a bug inside one of dependencies - fido2>=0.7.0,<=0.7.3
Possible workaround would be to install fido2==0.7.0 first and then proceed with installation

## Steps to Reproduce (for bugs)

1. Create new conda env
2. pip install gimme-aws-creds
3. See error

## Your Environment

* App Version used: 2.3.3
* Environment name and version: conda env 4.8.2
* Operating System and version: Windows 10

**Comment by nickagee** [comment]
I fixed this error on my windows 10 conda environment with the following steps:
`pip install fido2==0.7.0
pip install --upgrade gimme-aws-creds`

**Comment by FenryrMKIII** [comment]
I had the same issue. Solution

> I fixed this error on my windows 10 conda environment with the following steps:
> `pip install fido2==0.7.0`
> `pip install --upgrade gimme-aws-creds`
> 
> *edit: formatting

I had the exact same issue. Your proposal fixed it

**Comment by Sector95** [comment]
Fix in latest version (v2.3.4), thanks!
