### ISSUE TITLE
Move GimmeAWSCreds class to allow Testing

### ISSUE THREAD

**Issue by SectorNine50** [Nike-Inc/gimme-aws-creds#20]
`bin/gimme-aws-creds` needs to be refactored to move the `GimmeAWSCreds` class into another file within the gimme_aws_creds package to allow testing of the functions within the `GimmeAWSCreds` class.  This is due to the fact that the hyphens in `bin/gimme-aws-creds` does not allow you to import the module for testing.

This work is being done in the [no-role-handling](https://github.com/Nike-Inc/gimme-aws-creds/tree/no-role-handling) branch.

**Comment by SectorNine50** [comment]
See #22

**Comment by anners** [comment]
changes have been merged
