### ISSUE TITLE
Add gimme-aws-creds to Arch User Repository

### ISSUE THREAD

**Issue by mastertinner** [Nike-Inc/gimme-aws-creds#204]
It would be great to have this tool in the [AUR](https://aur.archlinux.org/). Are there any plans to do so? If not, I could give it a try and come up with a `PKGBUILD` file.

**Comment by chrissnell-okta** [comment]
Here's my initial effort:

https://aur.archlinux.org/packages/gimme-aws-creds/

You will also need to install the `python-okta` package:

https://aur.archlinux.org/packages/python-okta/
