### ISSUE TITLE
Implement better error handling around App and Role selection.

### ISSUE THREAD

**Issue by SectorNine50** [Nike-Inc/gimme-aws-creds#21]
Currently, it's possible to insert any negative integer or non-integer values and bomb out the script.  Further, the script also crashes if no apps or roles are available to the user.

Work is being done in the [no-role-handling](https://github.com/Nike-Inc/gimme-aws-creds/tree/no-role-handling) branch.

**Comment by SectorNine50** [comment]
#22

**Comment by anners** [comment]
changes have been merged
