### ISSUE TITLE
Set Environment Variables instead of .aws/credentials 

### ISSUE THREAD

**Issue by AzySir** [Nike-Inc/gimme-aws-creds#210]
Apologies for the novice question, Is there a way to set the AWS credentials as environment variables from the CLI directly?

The ~/.aws/credentials are not ideal for my use cases.

**Comment by JDTAY** [comment]
aws-vault and aws-okta might be the better tools to use for setting credentials in your $env

aws-okta hasn't been supported by setment IO for a little while, but it still works atm though we're in the process of moving all our AWS Accounts to AWS SSO, and aws-vault works really well.

```aws-vault exec [account name in ~/.aws/config] -- [appname]```

e.g.

```aws-vault exec dev -- zsh```

Now my ZSH terminal has the credentials for the dev AWS account in it's $env. I'm not entirely sure if gimme-aws-creds offers this functionality off the top of my head.

**Comment by AzySir** [comment]
Thanks for your reply @JDTAY - I prefer awskeyring or aws-vault myself normally. But wasn't aware on how they would handle this scenario. As I'm generally used to using environment variables myself (much more beneficial in terms of containerisation) 

Also realised you can do a `export AWS_ACCESS_=``aws configure get profilename.aws_access_key_id` via CLI

I might just create a PR and add it in here? What do you think? Better than flipping through gimme-aws-creds then to aws-vault

**Comment by JDTAY** [comment]
Any time @AzySir 

Yeah I think that's not a bad idea :)

I haven't heard of awskeyring, I'll check it out.

**Comment by mhumeSF** [comment]
This already is available. Just `eval $(gimme-aws-creds)`. Make certain your output is set to export

From: https://github.com/Nike-Inc/gimme-aws-creds#usage
> You can automate the environnement variable creation by running $(gimme-aws-creds) on linux or iex (gimme-aws-creds) using Windows Powershell
