### ISSUE TITLE
Brew is running ahead of GitHub?

### ISSUE THREAD

**Issue by yermulnik** [Nike-Inc/gimme-aws-creds#256]
[Brew formulae](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gimme-aws-creds.rb) has version `2.3.5` of `gimme-aws-creds` though there's no respective release on GH yet(?)

## Expected Behavior
Brew formulae version matches releases list on GH

## Current Behavior
```
> brew outdated
gimme-aws-creds (2.3.4_1) < 2.3.5
```
## Possible Solution
:man_shrugging: 

## Steps to Reproduce (for bugs)
`brew up && brew outdated`

## Context
No information about new release as this hasn't been published on GH yet

## Your Environment
```
OS: macOS Catalina 10.15.6
Homebrew 2.5.6
```

**Comment by bwynsm** [comment]
hmm. We're tagged at 2.3.5 now.
Going to probably be pushing a new release with some more PRs _somewhat_ soon.

**Comment by yermulnik** [comment]
oh 🤔  but how do I figure out what changes were introduced in v2.3.5?
![image](https://user-images.githubusercontent.com/1274789/96905829-a5453b00-14a1-11eb-8bb4-7fc8f183cc6b.png)

**Comment by yermulnik** [comment]
oh, it's already there. nvm.
![image](https://user-images.githubusercontent.com/1274789/96905914-c0b04600-14a1-11eb-9130-fb0384c6444f.png)

**Comment by bwynsm** [comment]
I'll see if I can get the changes in there.
The changelog hasn't been updated in this repo. At all. So there's some significant work to be done there.

**Comment by yermulnik** [comment]
Thanks @bwynsm 
I went through commits to see what has changed though 😃

**Comment by bwynsm** [comment]
awesome. Thanks for your patience.

**Comment by yermulnik** [comment]
Wow, amazing! Thanks a bunch 🙇 
![image](https://user-images.githubusercontent.com/1274789/97021521-9ae77780-155b-11eb-92bd-c5ebdb48e201.png)
