### ISSUE TITLE
Use a single okta app and not need okta API keys.

### ISSUE THREAD

**Issue by bkruger99** [Nike-Inc/gimme-aws-creds#26]
Currently, an OKTA api key is need which may not be available to use.  Ideally, support to not require an API KEY and just read the SAML response for roles would be fine.   There is a drawback where you won't have a resolved AWS account id to alias as that information isn't provided.  Some other method to handle that would need to be done.

**Comment by onetinov** [comment]
Are you intending to work on this via a PR @bkruger99 ?  I may take a look if i get time.  I was thinking of basically dumping the output of the app query to work out what we are missing and then statically providing that via optional config variables.

**Comment by bkruger99** [comment]
@onetinov I do, but I won't get a chance to look at it before tomorrow at the earliest.  I'll have to get familiar with the code base, finally started to look at it yesterday.

**Comment by bwhaley** [comment]
The Okta API tokens leave a lot to be desired. The [token API is deprecated](https://developer.okta.com/docs/api/resources/tokens.html). Tokens must now be issued the the admin web console, and hence have administrative privileges and couldn't be distributed to users. I opened support case with Okta on this and they suggested Oauth or OpenID which seems like overkill. But obviously a solution that doesn't require an API token at all would be preferred.

Is any work being done on this? I'd be happy to take a stab at it if nobody else has put the effort forth.

BTW, thanks for this tool, it's just what I needed!

**Comment by bwhaley** [comment]
FYI - AWS has an answer for this now: https://github.com/awslabs/awsprocesscreds

**Comment by anners** [comment]
@bwhaley we are not currently working on this, but I will take a look at awsprocesscreds.

**Comment by bwhaley** [comment]
Also came across this one; https://github.com/Versent/saml2aws

**Comment by mdu42** [comment]
Hi,
I ve made some changes in the PR to handle app url without the need to use of an OKTA API Token.
