### ISSUE TITLE
save password to keychain formatting.

### ISSUE THREAD

**Issue by opsroller** [Nike-Inc/gimme-aws-creds#268]
When running the gimme-aws-creds, it will ask if you would like to save your password to your local keychain.

## Expected Behavior
The message should convey the default

Do you want to save this password in the keyring? (y/N) 

## Current Behavior
Currently the message displayed is

Do you want to save this password in the keyring? (y/n) 

## Possible Solution
Capitalize the N

## Steps to Reproduce (for bugs)
1. invoke gimme-aws-creds
2. it should ask for your password, enter it.
3. then you will be prompted for saving to your local keychain.
4. If you press enter with no input, what do you expect?

## Context
I have had many users come to me when presented with this option. They are afraid of continuing without checking with our team first.

## Your Environment
macOS, Linux, Windows.

**Comment by bakhodir1986** [comment]
How to change saved password in keyring?
