### ISSUE TITLE
Give ability to map aws account id to an alias - (pending on issue 26)

### ISSUE THREAD

**Issue by bkruger99** [Nike-Inc/gimme-aws-creds#27]
Provided work is done on issue 26, then the next step would be to have the ability to have an account id->alias mapping so you aren't stuck with . 1234567890:SomeRole .    This is incredibly useful if you happen to have the same role across multiple accounts so you aren't necessarily guessing which account you're assuming role into.  Mapping could be either part of config and really just needs to be key:value, but ability to specify an external file independent of config would be excellent as well.  (I hope to get working on 26 and this one)

**Comment by Sector95** [comment]
I guess I don't understand this problem fully-- don't you select the account prior to the role selection anyway?

**Comment by Sector95** [comment]
Understand now, discussion occurring in #51.
