### ISSUE TITLE
Webauthn breaks with latest version of fido2

### ISSUE THREAD

**Issue by twelvelabs** [Nike-Inc/gimme-aws-creds#275]
I reinstalled `gimme-aws-creds` this morning and started getting errors attempting to use my YubiKey (via `webauthn`) for MFA.

## Expected Behavior

I should be able to select `webauthn` as my MFA option.

## Current Behavior

Raises a `TypeError` about being unable to unpack `Fido2ClientAssertionSelection`. I no longer have the exact stacktrace, but it was due to [fido2 releasing version 0.9.0 today](https://github.com/Yubico/python-fido2/releases/tag/0.9.0) which includes breaking changes to [`Fido2Client.get_assertion`](https://github.com/Yubico/python-fido2/blob/63c3d8e360104ccb669da2100ee24f51c3663d9b/fido2/client.py#L644): it now returns a single object rather than a collection.

## Possible Solution

Simplest fix would be to [change the dependency to `<0.9.0`](https://github.com/Nike-Inc/gimme-aws-creds/blob/509f290b1b20bd3ef1d65a26ac29dfd2fca9eb52/requirements.txt#L7). I've made that change locally and confirmed it fixes the issue.

Otherwise you'll need to update to use the new `Fido2Client` interface and pin to `>=0.9.0`.

Sorry, y'all... dependencies are the worst 😞 

## Steps to Reproduce (for bugs)
1. pip install gimme-aws-creds==2.3.5 in a new virtualenv 
2. Attempt to authenticate and use webauthn for MFA

## Your Environment

* App Version used: v2.3.5
* Environment name and version: Python 3.7.3 (via Homebrew)
* Operating System and version: macOS 10.14.6

**Comment by gcbeltramini** [comment]
The requirement should have been `fido2>=0.8.0,<0.9.0` (instead of `fido2>=0.8.0,<=0.9.0`).
