### ISSUE TITLE
Docker build fails on cryptography module

### ISSUE THREAD

**Issue by mjreed-turner** [Nike-Inc/gimme-aws-creds#279]
## Expected Behavior
`docker build .` on a fresh clone of master branch should succeed

## Current Behavior
Build fails during install of cryptography module with `ModuleNotFoundError: No module named 'setuptools_rust'`

## Possible Solution
A search online will find a fair amount of discussion around a recent change to cryptography breaking builds. Some users reported that a newer pip version resolved the problem, but the alpine:python3.8 image has the latest version of pip and still triggers the error in this build. An alternative fix that does work is to add cryptography directly to requirements.txt, pinned to a version that predates the issue (`cryptography==3.3.2` works).

## Steps to Reproduce (for bugs)
1. clone https://github.com/Nike-Inc/gimme-aws-creds
2. From the top level of the cloned repo, Run `docker build .`

## Context
Unable to build docker image  

## Your Environment
* App Version used: 2.3.5
* Environment name and version: Docker Desktop for Mac 3.0.3
* Operating System and version: macOS Catalina 10.15.7

**Comment by mcormier** [comment]
I just solved this problem this morning locally.  I had to do the following to the docker file to get it to build.

    FROM python:3.8-alpine

    WORKDIR /opt/gimme-aws-creds

    COPY . .

    RUN apk --update add gcc musl-dev libffi-dev openssl-dev 

    #
    #  The Rust available by default in Alpine < 3.12 is older than the minimum supported version.
    #  https://cryptography.io/en/latest/installation.html
    # 
    RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo 

    RUN pip install cryptography
  
    RUN python setup.py install 

    RUN apk del --purge gcc musl-dev libffi-dev openssl-dev

    ENTRYPOINT ["/usr/local/bin/gimme-aws-creds"]`

**Comment by Sector95** [comment]
Fixed:
https://github.com/Nike-Inc/gimme-aws-creds/blob/91b094bcc65b2d27de54dd44540181f1b37887b3/Dockerfile
