### ISSUE TITLE
Cannot run gimme-aws-creds in Windows 10

### ISSUE THREAD

**Issue by MarkEvansHW** [Nike-Inc/gimme-aws-creds#289]
It worked in the past, so unclear on what changed. My system seems fine otherwise. When I run "gimme-aws-creds" at the command line, I get the message ""C:\Program"' is not recognized as an internal or external command, operable program or batch file."

I have uninstalled and reinstalled multiple times, but I continue to get this message. I see another issue that says there's a problem with python.exe (vs python3.exe) so not sure if this is related.

## Expected Behavior
ability to run gimme-aws-creds at command line in Windows 10

## Current Behavior
running gimme-aws-creds at command line results in message ""C:\Program"' is not recognized as an internal or external command, operable program or batch file."

## Steps to Reproduce (for bugs)
Not sure how to reproduce

## Context
Unable to run gimme-aws-creds

## Your Environment
 gimme-aws-creds-2.4.1
Windows 10 Enterprise, Version 1909, OS build 18363.1379

**Comment by Kipjr** [comment]
This is probably due to a space in `C:\Program Files\`, please use `'C:\Program Files\'`

**Comment by carterchiu** [comment]
In case anyone is here trying to resolve this same issue, [this](https://github.com/Nike-Inc/gimme-aws-creds/issues/257#issuecomment-838158689) solution from @kkrav3ts worked for me. Cheers!
