### ISSUE TITLE
Accounts in AWS-China not supported

### ISSUE THREAD

**Issue by epierce** [Nike-Inc/gimme-aws-creds#29]
AWS China and AWS GovCloud use separate API endpoints from the rest of AWS, including the STS endpoint for requesting temporary credentials.  `boto3.client` defaults to the standard endpoints, but can accept a region parameter to switch to one of the alternatives.

There needs to be a way to define the region on a per-account basis - you may have a user with access to accounts in China and other AWS regions.

**Comment by anners** [comment]
Is there a way to get the region from Okta?

**Comment by onetinov** [comment]
I dont see it in the okta returned json of enumerating the application.  There is an open request to add the specific application to the okta config to avoid needing to use the OKTA API key altogether.  If that is the case, could we additionally provide the aws region?

So for example - 
```
[DEFAULT]
okta_auth_server =
okta_org_url = https://orgname.okta.com
gimme_creds_server = internal
client_id =
write_aws_creds = True
cred_profile = role
aws_appname = Orgname us-east-1 AWS
aws_rolename = all

[cn-north-1]
okta_auth_server =
okta_org_url = https://orgname.okta.com
gimme_creds_server = internal
client_id =
write_aws_creds = True
cred_profile = role
aws_appname = Orgname cn-north-1 AWS
aws_rolename = all
aws_region = cn-north-1
```

Then gimme-aws-creds could be called with `--profile cn-north-1` and would get the optional aws_region config var.

Would that be reasonable?

**Comment by anners** [comment]
That sounds reasonable. The AWS domain for the console for China and GovCloud is different than the typical https://XXX.signin.aws.amazon.com/console, but that seems hacky to check each Okta app for the login url to determine if it is China or GovCloud.

**Comment by epierce** [comment]
I'm looking into mapping the ACS URL that's returned in the SAML response to the AWS partition.  If that works, the user won't need to do anything special to use accounts from China or GovCloud. The standard ACS endpoint is `https://signin.aws.amazon.com/saml`, while AWS-China uses `https://signin.amazonaws.cn/saml` and I assume there's another one for AWS-GovCloud

**Comment by anners** [comment]
@epierce perfect, I was hoping there would be something like that, all I could think of was the console urls that are defined in the app.

**Comment by anners** [comment]
GovCloud appears to be: https://signin.amazonaws-us-gov.com/saml

**Comment by anners** [comment]
PR #32 has been merged. Closing this issue.
