### ISSUE TITLE
Python-dateutil requirement conflict

### ISSUE THREAD

**Issue by rabbittsoup** [Nike-Inc/gimme-aws-creds#313]
## Expected Behavior

Minor updates to python-dateutil dependency should likely be allowed to help prevent cross-library dependency conflicts.  It's unclear to me why the requirement is <=2.8.1?  Is this possibly a bug?  Was this intended to be >=2.8.1,<3?

## Current Behavior

Restrictive python-dateutil requirement can cause cross-library conflicts when minor updates occur.  python-dateutil was updated to 2.8.2 with bug fixes, but gimme-aws-creds requires <=2.8.1, causing conflicts with other libraries that may require python-dateutil 2.8.2.
https://github.com/Nike-Inc/gimme-aws-creds/blob/94ca37dc7a836a49c19dd09ec879dec416280e36/requirements.txt#L2

## Possible Solution

Potentially update the requirement as python-dateutil>=2.8.1,<3.0.0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* App Version used:
* Environment name and version:
* Operating System and version:

**Comment by flying-sheep** [comment]
Hmm, no way to tell why that’s even there.

I expect reasons in a comment, or at least `git blame` to tell why something exists, but I just see the commit message “Nuclear Option.” nothing else.

I filed https://github.com/Nike-Inc/gimme-aws-creds/pull/346 to remove it, let‘s see

**Comment by ldeflandre** [comment]
This restrictive pin is forcing pip to install very old and broken gimme-aws-creds-2.0.2 now that latest python-dateutil is 2.8.2

It would be help greatly the developer experience to have this fixed.
