### ISSUE TITLE
Python 2.7 has been deprecated in AWS Lambda, upgrade scripts/docs to mention 3.x support?

### ISSUE THREAD

**Issue by sandwormusmc** [Nike-Inc/gimme-aws-creds#315]
Now that AWS has deprecated new Lambdas being created using Python 2.7, is there a plan to make the Lambda included in this project run in Python 3.x, or does it already?

https://aws.amazon.com/blogs/compute/announcing-end-of-support-for-python-2-7-in-aws-lambda

**Comment by epierce** [comment]
The lambda works with Python3.x
