### ISSUE TITLE
URL Validation logic is incorrect

### ISSUE THREAD

**Issue by mjreed-turner** [Nike-Inc/gimme-aws-creds#327]
## Expected Behavior
Invalid org URLs should be rejected by configuration action.

## Current Behavior
Any "https:" URL is accepted.

## Possible Solution
This line of code is incorrect (gimme_aws_creds/config.py:318):

                if url_parse_results.scheme == "https" and "okta.com" or "oktapreview.com" or "okta-emea.com" in okta_org_url:

Since "okta.com" is a truthy value, the expression returns true for any url with a scheme of "https".  If the domain name needs to be validated, the code would look something like this:

       scheme, host = url_parse_results.scheme, url_parse_results.netloc
       if scheme == "https" and (host.endswith("okta.com") or host.endswith("oktapreview.com") or host.endswith("okta-emea.com")):

## Steps to Reproduce (for bugs)
1. Run `gimme-aws-creds --config` and provide some invalid URL (e.g. `https://totally-made-up.url`) for  your organization's Okta URL. 
2. Observe that the URL is accepted and stored in the config file instead of rejected as invalid.

## Context
I don't know if validating org URLs against a hard-coded list of Okta TLDs is something this tool should be doing, but it currently appears to be trying to do that while not actually doing it. 

## Your Environment
* App Version used: 2.4.3
* Environment name and version: CPython 3.9.7
* Operating System and version: macOS Catalina 10.15.7

**Comment by epierce** [comment]
fixed in #375
