### ISSUE TITLE
Feature Request: Provide credential expiration in AWS_SHARED_CREDENTIALS_FILE and `--output export`

### ISSUE THREAD

**Issue by seanorama** [Nike-Inc/gimme-aws-creds#329]
## Expected Behavior

Provide the credential expiration in the AWS_SHARED_CREDENTIALS_FILE:

```ini
[myprofile]
aws_access_key_id             = ...
aws_secret_access_key         = ...
aws_session_token             = ...
aws_security_token            = ...
aws_credential_expiration     = 2022-01-26T13:21:45+00:00
```

And make available as `AWS_CREDENTIAL_EXPIRATION` in `gimme-aws-creds --output export`:

```
export AWS_CREDENTIAL_EXPIRATION="2022-01-26T13:21:45Z"
```

## Current Behavior

Expiration is not provided in AWS_SHARED_CREDENTIALS_FILE or Environment variables.

Without this, it's not possible to know if the credential has expired without attempting to use it.

## Possible Solution

Write the expiration, which is provided by the STS API and already in `gimme-aws-creds --output json) to the AWS_SHARED_CREDENTIALS_FILE.

## Context

This is already provided from the AWS STS API and from `gimme-aws-creds --output json`:

```json
{
  "shared_credentials_file": "/Users/seanroberts/.aws/credentials",
  "profile": {
    "name": "cu_cloud_users",
    "derived_name": "cuSRE",
    "config_name": "cu_cloud_users"
  },
  "role": {
    "arn": "...",
    "name": "...",
    "friendly_name": "",
    "friendly_account_name": ""
  },
  "credentials": {
    "aws_access_key_id": "...",
    "aws_secret_access_key": "...",
    "aws_session_token": "...",
    "aws_security_token": "...",
    "expiration": "2022-01-26T13:21:45+00:00"
  }
}
```

Some AWS SDKs already support the key-name `AWS_CREDENTIAL_PROCESS`:

1. Python (Boto3):
   1. https://github.com/boto/botocore/pull/1187 
   2.  https://github.com/boto/botocore/blob/f5a2177b0129eb53d7a77171300eddcad5d7848e/botocore/credentials.py#L1063
2. JavaScript:
   1. https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html#fromenv
   2. https://github.com/aws/aws-sdk-js-v3/blob/4839121633/packages/credential-provider-env/src/index.ts#L7

And a competitor, [saml2aws](https://github.com/Versent/saml2aws), provides this which allows it to know if a new token is needed:

```
[myprofile]
...
x_security_token_expires = 2021-12-03T11:42:37Z
```

This value can be used to determine if the session is still valid or needs to be renewed.

**Comment by seanorama** [comment]
In #300 @gcbeltramini has solved for the AWS_SHARED_CREDENTIALS_FILE.

Can we get this looked at? Many of us have created wrappers around `gimme-aws-creds` to provide this simple functionality.

**Comment by epierce** [comment]
this functionality was just merged into the main branch. The expiration time is stored as `x_security_token_expires` to match the value used in saml2aws
