### ISSUE TITLE
Accept y AND Y as affirmative response to keyring question

### ISSUE THREAD

**Issue by freeformz** [Nike-Inc/gimme-aws-creds#330]
It turns out keyring storage for me wasn't working and it was all because I was typing 'Y', not 'y'.

## Expected Behavior

entering 'Y' to the `Do you want to save this password in the keyring? (y/N)` should count as a yes.

## Current Behavior

entering 'Y' to the `Do you want to save this password in the keyring? (y/N)` counts as a no.

## Possible Solution

https://github.com/freeformz/gimme-aws-creds/pull/new/ffz/LowerCasekeyRingAnswer

## Steps to Reproduce (for bugs)

1. Run `gimme-aws-creds` with an empty keychain
2. When prompted to save the password in your keyring, enter 'Y'.
3. Re-run `gimme-aws-creds` and you'll have to re-enter your password and be prompted to save again.

## Context

This is obviously my mistake (BKAC problem), but IMNSHO, making this change is a good call from a UX perspective. If it helps even one other person then it's worth it.

## Your Environment

* App Version used: 2.4.3
* Operating System and version: macOS 12.0.1

**Comment by epierce** [comment]
fixed in #422
