### ISSUE TITLE
gimme-aws-creds not handling newer Okta OIE 

### ISSUE THREAD

**Issue by roboweaver** [Nike-Inc/gimme-aws-creds#345]
I get this message too when trying to use the new OIE Okta Identity Engine flow - I am also able to log in with the IDP directly from Okta to the console, but the gimme-aws-creds errors out just like above. I have been talking to Okta and it appears there is some change in the SAML flow with this rule enabled:

<img src=https://user-images.githubusercontent.com/3752123/145892320-318d8555-8d48-40f2-96e6-9e5bd1c68ad6.png>

Related to https://github.com/Nike-Inc/gimme-aws-creds/issues/331 but slightly different so figured I'd add another ticket

On the old flow in the browser, Okta prompts for login and a form is displayed for the auth type. On the new flow a screen is displayed that shows the options for login like this, and the code appears to be looking for a form field of "SAMLResponse" in the HTML - this seems like it has broken due to the HTML in the new flow being different than expected here. If MFA is disabled, then gimme-aws-creds works on this new flow.

<img src=https://user-images.githubusercontent.com/3752123/146024701-8cb027fb-9f40-4c79-8ca6-ec4a82711335.png>

**Comment by Eric-Vollrath** [comment]
![image](https://user-images.githubusercontent.com/71726354/183690704-503e64be-6004-4078-8b4c-aa95a4095a84.png)
If it helps, this is what Okta says about it.

**Comment by ronanfrench** [comment]
Hello, to clarify, is this issue fixable by a configuration in Okta flow for this app?

Has there been any work to support OIE in `gimme-aws-creds` ?

Many thanks!

**Comment by Eric-Vollrath** [comment]
Is there any update on this? I too want to upgrade to OIE, but losing aws-gimme-creds would be painful.

**Comment by epierce** [comment]
Okta released [okta-aws-cli](https://github.com/okta/okta-aws-cli) for orgs using OIE.  gimme-aws-creds will probably add support for OIE in the future, but for right now, okta-aws-cli is your best bet.

**Comment by epierce** [comment]
I'm testing a new version of gimme-aws-creds: https://github.com/Nike-Inc/gimme-aws-creds/tree/okta-identity-engine

Because of the changes in OIE, it has to use the browser-based authentication like okta-aws-cli, so you lose the non-interactive login functionality, but overall, it's working in my tests.  If I can get some additional people to test it out with OIE and let me know if it works for them, I would appreciate it.

**Comment by Dhruvan1217** [comment]
@epierce Thanks for bringing up the support for OIE, is it possible we can work out without the OKTA_API_KEY? I mean, can we not bring in the same `okta-aws-cli` like use of `okta.apps.read` for accessing the apps API?

**Comment by epierce** [comment]
@Dhruvan1217 Until Okta has a fix for allowing non-admins to use tokens generated with `okta.apps.read` scope (see [Issue 66](https://github.com/okta/okta-aws-cli/issues/66) in okta-aws-cli), I didn't see any reason to add the functionality.  Once that's fixed, I'll add the scope support and deprecate the use of OKTA_API_KEY for OIE domains

**Comment by epierce** [comment]
OIE support release in v2.6.0
