### ISSUE TITLE
gimme-aws-creds is very slow when processing large number of roles serially

### ISSUE THREAD

**Issue by eedgar** [Nike-Inc/gimme-aws-creds#349]
Gimme-aws-creds is pretty slow if your running in a large enterprise environment and you have access to lots of accounts and roles.  Sometimes it can seemingly take upwards of minutes to process them all.

## Expected Behavior
Be faster by running asyncronously

## Current Behavior
aws sts code is run serially and has to wait for slow responses from aws.

## Possible Solution
use threads to make the code faster in one particular area.

## Context
I have to run gimme-aws-creds daily and in order to deal with the slowness I have extensive filters setup etc.  But thats brittle and harder to maintain.

## Your Environment
Large number of accounts with a large number of roles inside the accounts.

* App Version used: latest main version of the git repo
* Operating System and version: ubuntu 20

**Comment by epierce** [comment]
#348 merged into master and all be released in 3.5.0
