### ISSUE TITLE
No indication when webauthn token touched.

### ISSUE THREAD

**Issue by zelch** [Nike-Inc/gimme-aws-creds#363]
There is a notable delay between a touch on the token, and the next indication that something is happening.

This may falsely lead a user to believe that they did not make contact with the device, or that it came loose in the USB port.

## Expected Behavior

We should print something once the touch has been registered.

## Possible Solution

PR incoming.

## Steps to Reproduce (for bugs)

Select a webauthn device for your MFA factor, note the delay between touching the device and the next output from gimme-aws-creds.

## Your Environment

* App Version used:
* Environment name and version:
* Operating System and version:

**Comment by slagiewka** [comment]
Although not directly confirming touch, the UX is better now with v2.5.0, thanks to #348 

```
❯ gimme-aws-creds           
Using password from keyring for email@email
Multi-factor Authentication required.
Pick a factor:
[0] webauthn: YubiKey 5 with NFC
[1] webauthn: YubiKey 5 with NFC
Selection: 1
Challenge with security keys ...

Touch your authenticator device now...

Authentication Success!
Saving arn:aws:iam as profile
Written profile profile to /Users/user/.aws/credentials
```

**Comment by epierce** [comment]
#419 fixes this
