### ISSUE TITLE
No way to disable keyring usage.

### ISSUE THREAD

**Issue by zelch** [Nike-Inc/gimme-aws-creds#364]
If a system keyring is supported, there is currently no way to prevent constant prompts to store your password.

## Expected Behavior

There should be some way to tell gimme-aws-creds not to keep prompting, or to not use the keyring at all.

## Current Behavior

If you do not wish to store your password in the system keyring, you have to keep saying so every single time you use gimme-aws-creds.

## Possible Solution

PR incoming.

## Steps to Reproduce (for bugs)

Remove any passwords currently stored in the system keyring for gimmie-aws-creds.

Authenticate with gimme-aws-creds, say no to saving your password, then authenticate with gimme-aws-creds again.

The prompt continues.

## Context

My company policy does not permit storage of the Okta password in a keyring, and I am currently unable to recommend that we switch to gimme-aws-creds given the likelihood that users will eventually say yes just to shut it up.

## Your Environment

* App Version used: Current gimme-aws-creds HEAD 96064117205a57a0e2850e7eb905070e1024691b.
* Environment name and version:
* Operating System and version:
MacOS Monterey, Version 12.5.1

**Comment by epierce** [comment]
This was added in v2.8.0

**Comment by JoeLyga** [comment]
Needs instructions on how to do this. I struggle with this constantly with the current version.
