### ISSUE TITLE
v2.4.5 release to PyPI

### ISSUE THREAD

**Issue by alexlatchford** [Nike-Inc/gimme-aws-creds#378]
Hey maintainers, firstly thanks for making & maintaining this project we've used it with great success here at Zillow :D 

One problem we're hitting though is a number of packages (mostly in the scientific computing community, ie `pandas` & `jupyter`) now require `python-dateutil>=2.8.1`. The good news is blocking issue is resolved (see [this PR](https://github.com/Nike-Inc/gimme-aws-creds/pull/346)), thanks for handling this!

The bad news is that change is still lingering in `master`, I'd like to request a release with the patches included since the `v2.4.4.` release back in Feb (see the delta [here](https://github.com/Nike-Inc/gimme-aws-creds/compare/v2.4.4...master)). We'd love to rely on an official release if possible!

Many thanks!

**Comment by eedgar** [comment]
@epierce Would it be possible to cut a new release?

**Comment by bobby-lin** [comment]
Bump this

**Comment by epierce** [comment]
I'm planning on releasing a new version the first week in January
