### ISSUE TITLE
MacOS:  Operation not permitted when running os.chmod(aws_config, 0o600)

### ISSUE THREAD

**Issue by DrewLandgraveCbsi** [Nike-Inc/gimme-aws-creds#384]
I have pyenv installed using python 3.8.13. When I run gimmie-aws-creds it writes the file in ~/.aws/credentials fine but when it makes it to the next step on the process I get the following stack trace

```
Traceback (most recent call last):
  File "/Users/ME/.pyenv/versions/3.8.13/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/Users/ME/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 471, in run
    self._run()
  File "/Users/ME/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 821, in _run
    self.write_aws_creds_from_data(data)
  File "/Users/ME/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 187, in write_aws_creds_from_data
    self._write_aws_creds(
  File "/Users/ME/.pyenv/versions/3.8.13/lib/python3.8/site-packages/gimme_aws_creds/main.py", line 148, in _write_aws_creds
    os.chmod(aws_config, 0o600)
PermissionError: [Errno 1] Operation not permitted: '/Users/ME/.aws/credentials'
```

It's failing when it's trying to execute line 148

## Expected Behavior
The script should execute completly

## Current Behavior
Script breaks at line main.py line 148

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)

1. Follow install instructions
2. Follow Config instructions
3. Run gimmie-aws-creds
5. See error after the authentication completes

## Your Environment

* App Version used: 2.5
* Environment name and version: zsh 5.8.1 (x86_64-apple-darwin22.0) Using iTerm terminal
* Operating System and version: MacOS Ventura 13.1

**Comment by DrewLandgraveCbsi** [comment]
I should not that the credentials file writes successfully and is being used correctly. The error message is just a bit annoying

**Comment by DrewLandgraveCbsi** [comment]
May have found the issue. The ~/.aws/credentials file had the owner as root rather than myself. I'll leave this open is this isn't the correct solution. Feel free to close if it is

**Comment by epierce** [comment]
`~/.aws/credentials` should be owned by your account, not root. It sounds like the permissions on your credentials file allowed you to write to it, but the `chmod` command failed because you're not the owner
