### ISSUE TITLE
Is email for mfa supported?

### ISSUE THREAD

**Issue by elishagreenwald** [Nike-Inc/gimme-aws-creds#394]
Quick sanity check - sms works fine (thank you!) but I can't do email for mfa. Is it supposed to work? Thanks!

## Expected Behavior
When selecting email for mfa it should send an email and prompt for the code.

## Current Behavior
It fails with an error `AttributeError: 'NoneType' object has no attribute 'get'` Please see attached logs.
[logs.txt](https://github.com/Nike-Inc/gimme-aws-creds/files/11354082/logs.txt)

## Context
I'm trying to use email for mfa. Please see config file attached.
[config_file.txt](https://github.com/Nike-Inc/gimme-aws-creds/files/11354083/config_file.txt)

## Your Environment

* App Version used: 2.5
* Environment name and version: Python 3.9.13
* Operating System and version: macos ventura 13.3.1

**Comment by epierce** [comment]
No one has implemented Email as a factor yet, but we'd welcome any PRs adding it.

**Comment by epierce** [comment]
This will be included in the next release
