### ISSUE TITLE
v2.6.0 build failure with Homebrew

### ISSUE THREAD

**Issue by p-linnane** [Nike-Inc/gimme-aws-creds#395]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v2.6.0 of gimme-aws-creds, we are encountering a build failure.
## Expected Behavior
gimme-aws-creds builds successfully

## Current Behavior
The build fails:
```
  ==> /opt/homebrew/Cellar/gimme-aws-creds/2.6.0/libexec/bin/pip install -v --no-deps --no-binary :all: --use-feature=no-binary-enable-wheel-cache --ignore-installed /private/tmp/gimme-aws-creds-20230503-42429-122748k/gimme aws creds-2.6.0
  Using pip 23.0.1 from /opt/homebrew/Cellar/gimme-aws-creds/2.6.0/libexec/lib/python3.11/site-packages/pip (python 3.11)
  Processing /private/tmp/gimme-aws-creds-20230503-42429-122748k/gimme aws creds-2.6.0
    Preparing metadata (setup.py): started
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/private/tmp/gimme-aws-creds-20230503-42429-122748k/gimme aws creds-2.6.0/setup.py", line 16, in <module>
        long_description=open("LONG_DESCRIPTION.md").read(),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'LONG_DESCRIPTION.md'
    error: subprocess-exited-with-error
```

## Possible Solution
It appears the release on PyPI, which we build from, is missing the `LONG_DESCRIPTION.md` file. This appears to be causing the failure.

## Steps to Reproduce (for bugs)
See above

## Context
Relates to https://github.com/Homebrew/homebrew-core/pull/130108

## Your Environment

* App Version used: v2.6.0
* Environment name and version: Homebrew CI environment
* Operating System and version: macOS 11, 12, and 13, and Ubuntu 22.04.

**Comment by epierce** [comment]
v2.6.1 was just released and should resolve this issue
