### ISSUE TITLE
Feature request: Redirect url for Okta device authorization to the browser

### ISSUE THREAD

**Issue by archellebatiller** [Nike-Inc/gimme-aws-creds#403]
Hi team, thank you for your amazing work on this project and for continually improving it!

With regards to the change in v2.6.0, is it possible to add a redirect functionality for the Okta device authorization?

## Expected Behavior
Whenever the url prompts, automatically redirect to the preferred browse and enter the code. This would take you directly to the MFA prompt, making the process more user-friendly.

## Current Behavior
Whenever performing the command, the ff. message prompts:

```
Open the following URL to begin Okta device authorization:

https://$OKTA_DOMAIN/activate?user_code=$USER_CODE
```
This would require us to manually go to the browser and do a few clicks before signing in.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* App Version used:
* Environment name and version:
* Operating System and version:

**Comment by epierce** [comment]
try `gimme-aws-creds --open-browser` - that should open your default browser to the correct Okta page with the authorization code already filled in.  The next release will have `open_browser` as a config file option so you won't have to specify it on the command line all the time.
