### ISSUE TITLE
Authentication success message is gone

### ISSUE THREAD

**Issue by slagiewka** [Nike-Inc/gimme-aws-creds#410]
## Expected Behavior

See `Authentication Success!` message when authentication was successful, but profiles are not yet written.

## Current Behavior

No interactive confirmation - silence between MFA interaction and writing profiles finished.

## Possible Solution

Restore the output 

## Context

Log was added in https://github.com/Nike-Inc/gimme-aws-creds/commit/055fc86283ea906e7045b1706b724d9837113dd4 / https://github.com/Nike-Inc/gimme-aws-creds/pull/348
It help to remediate UX issues described in https://github.com/Nike-Inc/gimme-aws-creds/issues/363
Removed in https://github.com/Nike-Inc/gimme-aws-creds/pull/392

## Your Environment

* App Version used: 2.6.1

**Comment by epierce** [comment]
The next release will fix this - it'll respond as soon as you touch the token
