### ISSUE TITLE
missing sdist for 2.7.1 release on pypi

### ISSUE THREAD

**Issue by chenrui333** [Nike-Inc/gimme-aws-creds#423]
👋 looks like sdist is missed for the latest release on pypi, raise an issue for awareness. Thanks!

**Comment by epierce** [comment]
I'm looking into it - the initial upload to Pypi had issues and now I'm having trouble redeploying since the binary distribution is already there.

**Comment by chenrui333** [comment]
why not just create a new release? like 2.7.2?

**Comment by chenrui333** [comment]
any update on this thread?

relates to https://github.com/Homebrew/homebrew-core/pull/139795

**Comment by epierce** [comment]
v2.7.2 with source was just released
