### ISSUE TITLE
Unable to use comments in .okta_aws_login_config

### ISSUE THREAD

**Issue by guinuxbr** [Nike-Inc/gimme-aws-creds#434]
## Expected Behavior
Considering that [configparser](https://docs.python.org/3/library/configparser.html) syntax is being used, I was expecting to be able to have comments in the file  `.okta_aws_login_config` by using "#" or ";"

## Current Behavior
As soon as I run the container, all comments added to `.okta_aws_login_config` are overwritten.

## Possible Solution
It would be nice to handle the comments possibly ignoring the characters "#" and/or ";" while parsing the configuration file.

## Steps to Reproduce (for bugs)
1. Add comments to .okta_aws_login_config using  "#" and/or ";".
2. Run `gimme-aws-creds -p profile_name`
3. Check  `.okta_aws_login_config` and the comments are gone.

## Context
This is a "nice to have" when you are dealing with several different profiles. It would be nice to have the ability to add comments to make it easier to understand details about the AWS Role being assumed. It would also help to onboard new colleagues when sharing `.okta_aws_login_config`.

## Your Environment
* App Version used: `2.7.2`
* Environment name and version: `Docker Engine 24.0.6`
* Operating System and version: `Windows 10 Pro 22H2`

**Comment by epierce** [comment]
I'm not able to replicate this - comments starting with "#" and ";" stay in the file unless I run `--configure` (which I would expect to clear comments and write out a fresh config block)

**Comment by epierce** [comment]
Closing this since we haven't heard anything back

**Comment by guinuxbr** [comment]
Sorry, mate. I thought I had already answered this.
I've tested the latest version, and it worked fine. I don't know what caused the issue before.
Thank you anyway.
