### ISSUE TITLE
400 Client Error: Bad Request for url https://trial-888888.okta.com/oauth2/v1/token 

### ISSUE THREAD

**Issue by maisam94** [Nike-Inc/gimme-aws-creds#441]
Device not activated
Your device cannot be activated because of an internal error when running the following command:
./gimme-aws-creds

following is configuration file 
okta_org_url = https://trial-888888.okta.com
okta_auth_server = default
client_id = 0.....7
gimme_creds_server = https://trial-888888.okta.com/home/amazon_aws/0....7/272
aws_appname =
aws_rolename =
write_aws_creds = True
cred_profile = role
okta_username =
app_url =
resolve_aws_alias = True
include_path = False
preferred_mfa_type =
remember_device = n
aws_default_duration = 43200
output_format =
force_classic = False
open_browser = True
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* App Version used:
* Environment name and version:
* Operating System and version:

**Comment by epierce** [comment]
Do you see any errors in the Okta logs?  That error message is not getting generated by gimme-aws-creds, so it must be coming back from Okta

**Comment by maisam94** [comment]
Yes, the error in the OKta logs is "[FAILURE]: user_not_assigned

**Comment by epierce** [comment]
your configuration is incorrect.  You should have:
`gimme_creds_server = appurl`
and
`app_url = https://trial-888888.okta.com/home/amazon_aws/0....7/272`

That will request the SAML login for that Okta app after initial authentication
