### ISSUE TITLE
Make the configure option non-interactive

### ISSUE THREAD

**Issue by jcreyf** [Nike-Inc/gimme-aws-creds#45]
Add support of environment variables and/or command line arguments to set all configuration options so that the tool can be used in an automated environment.
Have the script look for the below variables and have it auto-generate the configuration section in `~/.okta_aws_login_config` if not there yet and if it has everything it needs to do so.  Then also have it generate the AWS credentials with these arguments in the same run.

This should allow for a much higher level of automation.

```
export AWS_APPNAME="..."
export AWS_ROLENAME="arn:aws:iam::..."
export CLIENT_ID="..."
export CRED_PROFILE="..."
export GIMME_CREDS_SERVER="https://..."
export OKTA_AUTH_SERVER="..."
export OKTA_ORG_URL="https://..."
export OKTA_USERNAME="..."
export WRITE_AWS_CREDS="True|False"
```

**Comment by johntheisennike** [comment]
The ability to make this non-interactive must also extend to the MFA `Pick a factor` requirement as well.

**Comment by Sector95** [comment]
The MFA piece may be a large hurdle, I'm not entirely sure how we'd handle that.  Maybe just make the automated execution of the script fail if MFA is required.

**Comment by epierce** [comment]
If you're passing all the config variables into the environment, why not just create the `~/.okta_aws_login_config` with a shell script?

**Comment by Sector95** [comment]
That's a good point-- With the recent changes to the script you can get credentials with no further interaction after the initial call, so this might not be necessary.

If someone comes up with a use case where creating the config file is too burdensome/not possible, let us know and we'll revisit this.
