### ISSUE TITLE
open_browser doesn't work from config file

### ISSUE THREAD

**Issue by deepskyblue86** [Nike-Inc/gimme-aws-creds#450]
`open_browser` doesn't work from config file

## Expected Behavior
When adding `open_browser = True` in .okta_aws_login_config it will be honored

## Current Behavior
`open_browser` doesn't work from config file

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* App Version used: 2.8.0
* Environment name and version:
* Operating System and version:

**Comment by epierce** [comment]
This fix will be release in 2.8.1
