### ISSUE TITLE
version 2.8 not available through brew on macOS

### ISSUE THREAD

**Issue by carlo1313** [Nike-Inc/gimme-aws-creds#452]
Is there a way to make brew on macOS installing the latest gimme-aws-creds 2.8?

## Expected Behavior
brew on macOS should install the latest version 2.8 of gimme-aws-creds
`brew install gimme-aws-creds`

## Current Behavior
```
Warning: gimme-aws-creds 2.7.2_3 is already installed and up-to-date.
To reinstall 2.7.2_3, run:
  brew reinstall gimme-aws-creds
```

## Possible Solution
?

## Steps to Reproduce (for bugs)
call
`brew install gimme-aws-creds`

## Context
we require latest changes in 2.8

## Your Environment
* Operating System and version: macOS Monterey 12.7.3

**Comment by epierce** [comment]
2.8.1 should be available in Homebrew when it is released next week
