### ISSUE TITLE
gimme-aws-creds version 2.8.0 fails with OAuth Client ID is required for Okta Identity Engine domains

### ISSUE THREAD

**Issue by sushraju** [Nike-Inc/gimme-aws-creds#454]
## Expected Behavior
Version 2.7.2 worked as expected reading the `force_classic = True` parameter from `.okta_aws_login_config`.  But 2.8.0 does not honor that anymore and fails.

## Current Behavior
We picked up the new version `2.8.0` fails with the following error:
```
OAuth Client ID is required for Okta Identity Engine domains.  Try running --config again.
```

In the latest version, only running `gimme-aws-creds` explicitly with `--force-classic` on the command line works.  That's seems like a regression from the previous version(s).

## Steps to Reproduce (for bugs)

Run `gimme-aws-creds 2.8.0` with `force_classic = True` in `.okta_aws_login_config`.

## Your Environment

* App Version used: 2.8.0
* Operating System and version:  RHEL 8

**Comment by epierce** [comment]
the fix for this issue will be available in 2.8.1
