### ISSUE TITLE
v2.8.0 not available via Brew

### ISSUE THREAD

**Issue by ewanleaver** [Nike-Inc/gimme-aws-creds#455]
brew install gimme-aws-creds still installs v2.7.2_3

## Expected Behavior
brew install gimme-aws-creds should install the latest release (v2.8.0)

## Current Behavior
Version 2.7.2_3 is the highest version available

## Possible Solution
Bottle 2.8.0 and make available via brew

## Steps to Reproduce (for bugs)
1. brew install gimme-aws-creds
2. Version 2.7.2_3 is installed

## Context
I wish to use the 'acc' name for credential profiles, which was added as a feature in v2.8.0.

**Comment by epierce** [comment]
2.8.1 should be available in Homebrew when it is released next week
