### ISSUE TITLE
Format of AWS profiles has changed in version 2.8.0

### ISSUE THREAD

**Issue by rcollier-goodrx** [Nike-Inc/gimme-aws-creds#459]
We've received reports from developers that the format of AWS profiles has changed from this:

`aws-account-/role_name`

to this:

`aws-account-role_name`

This has caused some frustration because documentation and automation scripts reference the format prior to 2.8.0. When I look at the release notes for 2.8.0, I'm not seeing an explanation of why this change was made (maybe I missed it, please share if you can). 

## Expected Behavior

Profile names to match this format `aws-account-/role_name`, not the new one that was introduced in 2.8.0.

## Current Behavior

Profile names are being written out as `aws-account-role_name` which is a deviation from the previous format.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

This change has caused unexpected problems in the way some of our automation scripts work because they assume the format that existed in versions prior to 2.8.0 was stable. 

## Your Environment

* App Version used:
* Environment name and version:
* Operating System and version:

* App Version used: 2.8.1.1
* Environment name and version: N/A
* Operating System and version: MacOS Sonoma 14.2.1, Apple Silicon

**Comment by epierce** [comment]
This is fixed in master - When reading the config file, True and False were read in as Strings instead of Booleans.  That was changed in 2.8.0 but the comparisons for `include_path` and `resolve_alias` were missed.
