### ISSUE TITLE
AWS Format Roles Bug Fix for Homebrew

### ISSUE THREAD

**Issue by ajidevelop** [Nike-Inc/gimme-aws-creds#462]
I believe the initial bug has been addressed in #459, but was just wondering if there was going to be another release to fix the issue on homebrew. Unless there's a way to compile a formula locally and run the working version on master.

## Expected Behavior

Bug fix for #459 is implemented when running `brew install gimme-aws-creds`

## Current Behavior

Running `brew install gimme-aws-creds` still has the profile formatting error`

## Possible Solution

Update release version

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

A lot of automation scripts are failing and it seems the only workaround is install a python version and switching virtualenvs before running `gimme-aws-creds`

## Your Environment

* App Version used: 2.8.1.1
* Environment name and version: N/A
* Operating System and version: MacOS Sonoma 14.2.1, Apple Silicon

**Comment by flyaroundme** [comment]
Have the same on the pip installation

**Comment by flyaroundme** [comment]
Ah, I see it is fixed in master, but is not yet released

**Comment by epierce** [comment]
2.8.2 has been released
