### ISSUE TITLE
gimme-aws-creds gives error

### ISSUE THREAD

**Issue by Alakas** [Nike-Inc/gimme-aws-creds#47]
APFJGTF18C63AD:gimme-aws-creds asaran$ gimme-aws-creds
Okta username must be an email address.

We are expected to see the prompt for email address, but instead of asking for the email, it is giving me the errorin okta.py . line #510.

**Comment by Sector95** [comment]
This is tied to #48

**Comment by epierce** [comment]
Do you have an `OKTA_USERNAME` environment variable set? gimme-aws-creds will read that variable if it's set instead of asking for a username.
