### ISSUE TITLE
Store Username and Factor Option in Configuration

### ISSUE THREAD

**Issue by Sector95** [Nike-Inc/gimme-aws-creds#53]
In an effort to make the workflow as quick and simple as possible, we should allow the user to store their username, and multi-factor of choice as part of the configuration.  This will allow really painless refreshing/changing of credentials.

For example:
```shell
$ gimme-aws-creds.py --profile lab
Using password from keyring for <user>
Authentication Success!  Calling Gimme-Creds Server...
Multi-factor Authentication required.
Okta Verify push sent...
writing role <role> to <credfile>
```

The only interaction here would be with the MFA factor.

**Comment by Sector95** [comment]
Covered in #55

**Comment by epierce** [comment]
#55 adds this functionality
