### ISSUE TITLE
Getting gimme-aws-creds to work on windows

### ISSUE THREAD

**Issue by aishajackson** [Nike-Inc/gimme-aws-creds#56]
I am able to get everything to work - install, configuration. But, after running gimme-aws-creds, it gets stuck after the username. It never asks for the password.

**Comment by Sector95** [comment]
Odd, and you never get an error?  What version of Windows are you using? I just tried the latest version on Windows 10 version 1703 and it worked as expected.

At that part of the process, it's checking `keyring` for an existing credential, which uses the underlying Windows Credential Locker.  Makes me wonder if for some reason that subsystem is hanging.
