### ISSUE TITLE
DUO factor is not listed

### ISSUE THREAD

**Issue by seb-steuer** [Nike-Inc/gimme-aws-creds#57]
Hi,

I have configured gimme-aws-creds as follows:

[DEFAULT]
okta_username = xxxxxx
okta_org_url = https://xxxxx.okta.com
gimme_creds_server = appurl
app_url = https://xxxxx.okta.com/home/amazon_aws/xxxxxxxxxxxxxxxxxxxx/xxx

when I run the software i get:
Password for xxxxxxxx:
Authentication Success! Getting AWS Accounts
Multi-factor Authentication required.
Pick a factor:
Selection: 0
Traceback (most recent call last):
  File "/home/xxxxxxxx/.local/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/home/xxxxxxxx/.local/lib/python3.5/site-packages/gimme_aws_creds/main.py", line 434, in run
    saml_data = okta.get_saml_response(aws_app['links']['appLink'])
  File "/home/xxxxxxxx/.local/lib/python3.5/site-packages/gimme_aws_creds/okta.py", line 426, in get_saml_response
    api_response = self.stepup_auth(url, state_token)
  File "/home/xxxxxxxx/.local/lib/python3.5/site-packages/gimme_aws_creds/okta.py", line 85, in stepup_auth
    flow_state['stateToken'], flow_state['apiResponse'])
  File "/home/xxxxxxxx/.local/lib/python3.5/site-packages/gimme_aws_creds/okta.py", line 260, in _next_login_step
    return self._login_multi_factor(state_token, login_data)
  File "/home/xxxxxxxx/.local/lib/python3.5/site-packages/gimme_aws_creds/okta.py", line 361, in _login_multi_factor
    factor = self._choose_factor(login_data['_embedded']['factors'])
  File "/home/xxxxxxxx/.local/lib/python3.5/site-packages/gimme_aws_creds/okta.py", line 516, in _choose_factor
    return factors[int(selection)]
IndexError: list index out of range

It seems it authenticate properly but the factor list is empty but I have DUO properly configured and AWS console access through Okta requires DUO MFA and that works properly (all methods - push, text, call and code)

kind regards
Sebastian

**Comment by epierce** [comment]
I don't have an Okta instance with Duo integration enabled, but Okta only supports Duo as a `web` factor (https://developer.okta.com/docs/api/resources/factors#supported-factors-for-providers), which mans it has to be embedded in an iFrame.  Unless there's some other way to interact with Duo (which would also involve another level of MFA device selection), I don't see any way it would work from a CLI app.

**Comment by jimsmith** [comment]
Hello,

Would this help (I'm by no means a s/w developer but seems this has it working - haven't used it myself though)
https://github.com/segmentio/aws-okta/blob/master/lib/duo.go#L52-L55

**Comment by Sector95** [comment]
That does look like a good option, but we'll realistically need someone with direct access to Duo to put a PR together.

**Comment by seb-steuer** [comment]
Yes, happy to be a guinea pig :)

**Comment by brysontyrrell** [comment]
I'm at an org where we are using Okta and Duo. If any of the developers on this project are willing to provide some guidance I will take a stab at building in support for Duo. Losing access to this tool and needing to move to the Java based one has been disheartening.

**Comment by PVSec** [comment]
This is one way of handling it https://github.com/nathan-v/aws_okta_keyman/blob/master/aws_okta_keyman/duo.py

**Comment by seb-steuer** [comment]
Yep. I'm aware of the recent aws_okta_keyman duo support addition.
Not had a chance to test it yet but had a quick discussion within my team and they dont seem to be very keen on changing the tool :)

**Comment by PVSec** [comment]
What I meant was for the maintainers of gimme-aws-creds to use that code, with proper attribution, to speed up this feature request. In fact, I already modified the gimme-aws-creds code locally to add duo support at it works very well.

**Comment by Sector95** [comment]
Update on this for those watching at home:
We're making sure we're good-to-go on the legal side of things. Once we get the green light, we'll get #152 merged in and get a new release out the door.

**Comment by Sector95** [comment]
Duo support out the door in v2.2.0.  Appreciate the help to all involved!
