### ISSUE TITLE
not able to see credentials

### ISSUE THREAD

**Issue by jaychoudharymhe** [Nike-Inc/gimme-aws-creds#63]
have installed latest version of gimme-aws-creds. 

**using python version - Python 3.5.0**

not seeing credentials being generated in .aws/credentials. In config file I have "write_aws_creds = True"

If I set it to false I don't see credentials on stdout

**Comment by epierce** [comment]
Are you getting any errors? If you're not getting credentials on stdout either, the process is likely dieing before it gets to that point in the code.

**Comment by roboweaver** [comment]
We're seeing the same thing with one user here - how do we debug this ?

User is not getting prompted for profile and not seeing the message about writing to the credential file

**Comment by roboweaver** [comment]
Another thing of note is that he has to add the --insecure flag, which makes little or no sense to me since our Okta server is secure and I've never seen an error on the SSL.

**Comment by roboweaver** [comment]
https://snag.gy/Mwtnu2.jpg - nothing after the success message

**Comment by Sector95** [comment]
Any updates on this?

**Comment by roboweaver** [comment]
He did some updates and that fixed the SSL error.

We got around the missing credentials file being missing with the workaround  on  this other issue: https://github.com/Nike-Inc/gimme-aws-creds/issues/62

I've added that to the troubleshooting section of our internal document for getting gimme-aws-creds to work.

**Comment by Sector95** [comment]
Got it.

Is the problem that the client isn't creating the `credential` file, or does it only occur when the `.aws` directory is also missing?
