### ISSUE TITLE
Unable to increase the exipry time of aws keys to 12 hours.

### ISSUE THREAD

**Issue by gmidha** [Nike-Inc/gimme-aws-creds#64]
Hi There,

I was informed that aws keys will expire after 12 hours of creation. I tried different options: 1. use default value, 2. add "aws_default_duration = 43200" in .okta_aws_login_config.

My aws keys are expiring every hour. Can you please help me what configuration do I have to change to make sure keys are active for 12 hours from the time of creation.

Thanks,
Gaurav

**Comment by epierce** [comment]
You also need to change the `MaxSessionDuration` for each role you want to access.  If the value you've selected for `aws_default_duration` is greater than the session duration for the current role, gimme-aws-creds will display a warning and fallback to 3600 seconds.  There's more info on extended session expiration [here](https://aws.amazon.com/about-aws/whats-new/2018/03/longer-role-sessions/).

**Comment by gmidha** [comment]
Hi Eric,

I already set Maximum CLI/API session duration to 12 hours (43,200 seconds) for the role and after that I set aws_default_duration to 43200 in my local. But my keys are still expiring after an hour.

**Comment by satssin** [comment]
Hi Eric,
Every role is set up for 12hours session.
