### ISSUE TITLE
Re opening the case 64

### ISSUE THREAD

**Issue by satssin** [Nike-Inc/gimme-aws-creds#66]
Good Morning 

I already set Maximum CLI/API session duration to 12 hours (43,200 seconds) for the role and after that, I set aws_default_duration to 43200 in my local. But my keys are still expiring after an hour.

**Comment by epierce** [comment]
Looking into this, I think it's actually a bug in Boto: https://github.com/boto/botocore/issues/1158
It looks like Boto doesn't pass the `DurationSeconds` parameter when the assume_role call is actually being made, so the credentials always default to 3600 seconds

**Comment by satssin** [comment]
Should i involve AWS support?

Sent from my iPhone

On Jun 20, 2018, at 12:58 AM, Eric Pierce <notifications@github.com<mailto:notifications@github.com>> wrote:


Looking into this, I think it's actually a bug in Boto: boto/botocore#1158<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fboto%2Fbotocore%2Fissues%2F1158&data=01%7C01%7Csatish.kumar1%40mheducation.com%7C2524dafec0994012eb4508d5d66a72c6%7Cf919b1efc0c347358fca0928ec39d8d5%7C0&sdata=mjSplvednIhK4FLqckQb2OD%2FrZ1OwnXTxz00PUuYazI%3D&reserved=0>
It looks like Boto doesn't pass the DurationSeconds parameter when the assume_role call is actually being made, so the credentials always default to 3600 seconds

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNike-Inc%2Fgimme-aws-creds%2Fissues%2F66%23issuecomment-398624415&data=01%7C01%7Csatish.kumar1%40mheducation.com%7C2524dafec0994012eb4508d5d66a72c6%7Cf919b1efc0c347358fca0928ec39d8d5%7C0&sdata=dj%2BoPohgU87EDFyCPvKQRKoyy4Lzi8CzMRv2tCw1Vxo%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEQLekouChFoE49j-YMPHpixqKrMQZ7Mks5t-dZtgaJpZM4Ur0d8&data=01%7C01%7Csatish.kumar1%40mheducation.com%7C2524dafec0994012eb4508d5d66a72c6%7Cf919b1efc0c347358fca0928ec39d8d5%7C0&sdata=WOwcdNyvNBCg37boZa3DxGU6vzr6ZpLVKTE6WnhzMjs%3D&reserved=0>.

The information contained in this message may be confidential and/or constitute a privileged attorney-client document.  If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify McGraw-Hill Education immediately by replying to the message and deleting it from your computer.  Thank you.

**Comment by satssin** [comment]
Hi Eric,
It looks like the boto3 version 1.7.40 has this fix,
https://boto3.readthedocs.io/en/latest/reference/services/sts.html

however, gimme-aws-creds is complaining about the bot version when I am installing boto3 1.7.40.



gimme-aws-creds 1.0.11 has requirement boto3==1.4.4, but you'll have boto3 1.7.41 which is incompatible.
Installing collected packages: botocore, boto3
  Found existing installation: botocore 1.2.4
    Uninstalling botocore-1.2.4:
      Successfully uninstalled botocore-1.2.4
Successfully installed boto3-1.7.41 botocore-1.10.41
Rename-this-Mavericks-Mac:~/Downloads$

**Comment by Sector95** [comment]
Ah, the requirements were relaxed (should now pull down the latest version of boto3, assuming it hasn't gone to v2.0.0), but done so without a version bump so I bet it didn't pull down a new copy.

Since this fix was put in place in 1.7.40, we should probably move the minimum value to that, and version bump so people pick up the change.

**Comment by epierce** [comment]
Version 1.0.13 has the relaxed requirements for the boto3 version, so you should be able to update gimme-aws-creds and then update boto3 to the latest version.

Let us know if that resolves the issue for you and we'll bump the minimum version to boto3 to 1.7.40.

**Comment by satssin** [comment]
I just changed the version  and generated the keys , let see it works.

**Comment by Sector95** [comment]
Haven't heard anything, assuming we're good here.
