### ISSUE TITLE
Credentials are not being written to cred file when there is only 1 role assigned

### ISSUE THREAD

**Issue by seb-steuer** [Nike-Inc/gimme-aws-creds#68]
Hi,

If a user has only 1 role assigned in okta integration gimme-aws-creds successfully authenticate with PW and MFA and then exits with code 0 without writing to creds file.
If the user has at least 2 roles assigned in okta then the selection menu is displayed and everything is working
That is with the fresh installation (pip install git+git://github.com/Nike-Inc/gimme-aws-creds.git)

`
[xxx@gandalf:~]$  gimme-aws-creds
Password for xxx: 
Authentication Success! Getting AWS Accounts
Multi-factor Authentication required.
token:software:totp( GOOGLE ) : xxx@yy.yyyyyy.com selected
Enter verification code: 610660

[xxx@gandalf:~]$  ls -la .aws/
total 12
drwxrwxr-x.  2 xxx xxx   39 Jun 21 09:16 .
drwx------. 27 xxx xxx 4096 Jun 29 10:29 ..
-rw-------.  1 xxx xxx 43 Jun 21 09:16 config
-rw-------.  1 xxx xxx 56 Jun 21 09:16 credentials

[xxx@gandalf:~]$  more .aws/config
[default]
region = eu-west-1
output = text

[xxx@gandalf:~]$  more .aws/credentials
[default]
aws_access_key_id = 
aws_secret_access_key = 

[xxx@gandalf:~]$  more .okta_aws_login_config
[DEFAULT]
okta_username = xxx
okta_org_url = https://yyy.okta.com
preferred_mfa_type = token:software:totp
write_aws_creds = True
cred_profile = default
gimme_creds_server = appurl
app_url = https://yyy.okta.com/home/amazon_aws/zzzzzzzzzzzzzzzz/zzz
resolve_aws_alias = True
aws_default_duration = 28800
`

I believe this is not a config issue

kind regards
Sebastian

**Comment by uvreut** [comment]
Hi I added a new commit that should solve this.
I was seeing the same issue.

**Comment by seb-steuer** [comment]
Great, I'll test that in single role scenario soon

For now I've noticed that line 290:
https://github.com/Nike-Inc/gimme-aws-creds/blob/ec09f2f017a69f4f74be42523abc4857d996050b/gimme_aws_creds/main.py#L290

breaks the compatibility with python 3.5

maybe you could use
`print("Detected single role: {}".format(single_role))`
instead?

kind regards
Sebastian

**Comment by seb-steuer** [comment]
@uvreut I can confirm the fix has worked. thank you

kind regards
Sebastian
