### ISSUE TITLE
gimme-aws-creds freezes after entering the user name

### ISSUE THREAD

**Issue by shachar-i** [Nike-Inc/gimme-aws-creds#70]
The process freezes entirely without any console output.
I am on Windows 10 in a conda environment. Same configuration works for my colleagues on a Mac.

Any ideas?
I there any way to approach this without opening the code?

Thanks

**Comment by epierce** [comment]
The process is still running, it just doesn't return any output? Can you provide more details on your environment (Python version, etc.)?  I'll try to replicate the problem in a VM.

**Comment by shachar-i** [comment]
I think so. I have to kill my terminal every time (does not stop with ctrl+c).
I'm using conda python 3.6 and git bash terminal

Here's a pip list output for reference:
Package             Version   Location
------------------- --------- ------------------------
absl-py             0.2.2
asn1crypto          0.24.0
astor               0.6.2
awscli              1.15.59
backcall            0.1.0
beautifulsoup4      4.6.0
bleach              2.1.3
blinker             1.4
boto3               1.7.42
botocore            1.10.58
certifi             2018.4.16
cffi                1.11.5
chardet             3.0.4
click               6.7
colorama            0.3.9
configparser        3.5.0
cryptography        2.2.2
cycler              0.10.0
decorator           4.3.0
docutils            0.14
entrypoints         0.2.3
Flask               1.0.2
Flask-Mail          0.9.1
gast                0.2.0
gimme-aws-creds     1.0.13
grpcio              1.12.1
h5py                2.8.0
html5lib            1.0.1
idna                2.7
ipykernel           4.8.2
ipython             6.4.0
ipython-genutils    0.2.0
ipywidgets          7.2.1
itsdangerous        0.24
jedi                0.12.0
Jinja2              2.10
jmespath            0.9.3
jsonschema          2.6.0
jupyter-client      5.2.3
jupyter-core        4.4.0
jupyterlab          0.32.1
jupyterlab-launcher 0.10.5
Keras               2.2.0
Keras-Applications  1.0.2
Keras-Preprocessing 1.0.1
keyring             10.6.0
kiwisolver          1.0.1
Markdown            2.6.11
MarkupSafe          1.0
mathutils           2.78
matplotlib          2.2.2
mistune             0.8.3
nbconvert           5.3.1
nbformat            4.4.0
notebook            5.5.0
numpy               1.14.5
okta                0.0.4
opencv-python       3.4.1.15
pandas              0.23.1
pandocfilters       1.4.2
parso               0.2.1
pexpect             4.6.0
pickleshare         0.7.4
Pillow              5.1.0
pip                 10.0.1
prompt-toolkit      1.0.15
protobuf            3.6.0
ptyprocess          0.5.2
pyasn1              0.4.3
pycparser           2.18
Pygments            2.2.0
pymongo             3.6.1
pyOpenSSL           18.0.0
pyparsing           2.2.0
PySocks             1.6.8
python-dateutil     2.7.3
pytz                2018.4
pywin32-ctypes      0.1.2
pywinpty            0.5.4
PyYAML              3.12
pyzmq               17.0.0
requests            2.19.1
rsa                 3.4.2
s3transfer          0.1.13
scikit-learn        0.19.1
scipy               1.1.0
Send2Trash          1.5.0
setuptools          39.2.0
simplegeneric       0.8.1
simplejson          3.16.0
six                 1.11.0
sklearn             0.0
tensorboard         1.8.0
tensorflow          1.8.0
termcolor           1.1.0
terminado           0.8.1
testpath            0.3.1
tornado             5.0.2
traitlets           4.3.2
urllib3             1.23
wcwidth             0.1.7
webencodings        0.5.1
Werkzeug            0.14.1
wheel               0.31.1
widgetsnbextension  3.2.1
wincertstore        0.2

**Comment by Sector95** [comment]
Any news on this?

**Comment by shachar-i** [comment]
Nothing so far. I will eventually have to solve this (It's preventing me from migrating AWS accounts). @Sector95 - have you also experienced this?

**Comment by Sector95** [comment]
No, I've never ran into it myself, but I also don't run in a Conda environment (not sure how relevant that is ultimately).  I was going through the issue list doing cleanup and noticed this one was still open, figured I'd ping for an update.

**Comment by shachar-i** [comment]
OK. This is behind me. I believe what did the trick was installing Amazon's AWS CLI for windows using the [MSI installer:](https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html#install-msi-on-windows). Does this make sense? If so it should probably be added to the installation instructions...

gimme-aws-creds is actually pretty sweet now that it finally works. Thanks!

**Comment by jamesmccalltakeda** [comment]
@shachar-i - is that all you had to do to fix it? I'm running into this same issue now. I installed awscli via pip3 and gimme-aws-creds is freezing after submitting my Okta username.

**Comment by shachar-i** [comment]
Hi James, my issues seemed to have been Windows OS related.

In addition to above, on Windows, setting password to credentials manager works only via cmd or anaconda prompt - so first time login or after password change those consoles must be used (vs git-bash which is my console of choice).

If you are on Windows - try above and post any output you get here.

If you are on mac/linux you're likely experiencing a configuration issue of some sort (verify your `.okta_aws_login_config` correctness and perhaps try a different authentication method)
