### ISSUE TITLE
gimme-aws-creds does not work on Python 37

### ISSUE THREAD

**Issue by MelvinVermeer** [Nike-Inc/gimme-aws-creds#71]
Once I installed 36, things started working as expected.

**Comment by Sector95** [comment]
Saw this once before-- did you uninstall gimme-aws-creds prior to installing 3.7?

Also, if you could post a stack trace, that would help.

All of that aside, it appears as though one of our package dependencies, specifically `okta`, isn't yet available as a package for 3.7 yet.  We will have to check with that project to determine what their plan is.

**Comment by Sector95** [comment]
Appears that this is no longer an issue...  3.7 is running as expected now.
