### ISSUE TITLE
Improper Credential Name When Grabbing Creds for AWS China Accounts

### ISSUE THREAD

**Issue by AlexWIllini** [Nike-Inc/gimme-aws-creds#72]
Currently if you grab creds for any of the aws china accounts using a profile you've configured, the creds get stored in your .aws/credentials file as an arn instead of just the profile name.

This is because the name is set by removing the first portion of the role but is only hardcoded for "arn:aws:..." where aws china roles look like "arn:aws-cn:..."

Note: I already fixed this issue and am in the process of submitting a PR, currently going through the contributing guidelines

**Comment by Sector95** [comment]
Thanks for the PR!
