### ISSUE TITLE
gimme-aws-creds overwrites config file everytime

### ISSUE THREAD

**Issue by badbeeker** [Nike-Inc/gimme-aws-creds#77]
Running `gimme-aws-creds --configure -p <profile>` overwrites the entire configuration file.  This wipes out the default and other profiles you may have had.  I also noticed that when I updated to the latest version, it had wiped out my previous config file. 

Seems like the functionality changed with the latest release.  Previously, if you ran the `--configure` with a different profile name, it would be appended to the existing configuration file.  Now that is no longer the case and any run on `--configure` wipes out the entire file.

Could we get the old functionality back where the new configuration would be appended instead of the entire file being overwritten?

**Comment by El-Dringo-Brannde** [comment]
@badbeeker Sounds like a regression, I'll look into it. Can you specify the last version you used, and the version you are experiencing the bug on?

**Comment by Ghazgkull** [comment]
This bug eliminates the ability to use `gimme-aws-creds --configure` to set up multiple profiles. The last profile you configure always overwrites the entire `~/.okta_aws_login_config` file.

As a workaround, I've found that you can manually copy in multiple profile blocks and `gimme-aws-creds` will correctly process them so you can use `gimme-aws-creds --profile <profile>` again.

**Comment by Ghazgkull** [comment]
Little more detail on the workaround for anyone trying to do it:

1. Run `gimme-aws-creds --configure` and create a named profile.
2. Run `gimme-aws-creds --profile <profile> --register_device` to get your device_token configured.
3. Open `~/.okta_aws_login_config` in your favorite editor.
4. Copy/paste the profile that's in the config and make whatever changes you want for additional profiles. In my experience, a single blank line between profiles works.

**Comment by El-Dringo-Brannde** [comment]
Remediated in commit 72d64c4b3009b59b51e93e826a208c5bac29b9f1
and PR https://github.com/Nike-Inc/gimme-aws-creds/pull/103

**Comment by Sector95** [comment]
Fix will be available in the v1.1.3 release.
