### ISSUE TITLE
Running gimme-aws-creds --register_device replaces all existing configuration

### ISSUE THREAD

**Issue by jrduncans** [Nike-Inc/gimme-aws-creds#79]
Similar to #77 except even more surprising. After updating to version 1.1.0 I received the error `No device token in configuration.  Try running --register_device again.` After running `gimme-aws-creds --register_device` all of my profiles were gone from my config file.

**Comment by dogonthehorizon** [comment]
I've encountered this behavior on commit `01d7e22` as well.

**Comment by dowdell** [comment]
Issue still present in version `1.1.1` (installed with `pip3`)

**Comment by Sector95** [comment]
This should be fixed in 1.1.2; see #103.
