### ISSUE TITLE
Getting the following error

### ISSUE THREAD

**Issue by arun-siv** [Nike-Inc/gimme-aws-creds#85]
Hi  Team,
I am getting the following error when approving from okta

Okta Verify push sent...
Traceback (most recent call last):
  File "gimme-aws-creds.py", line 17, in <module>
    GimmeAWSCreds().run()
  File "c:\MyProgs\myvenv\lib\site-packages\gimme_aws_creds\main.py", line 432, in run
    scopes=['openid']
  File "c:\MyProgs\myvenv\lib\site-packages\gimme_aws_creds\okta.py", line 220, in auth_oauth
    url_parse_results = urlparse(response.headers['Location'])
  File "c:\MyProgs\myvenv\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'

**Comment by arun-siv** [comment]
What should i configure for client id and oAuth server?
(myvenv) c:\MyProgs\myvenv\Scripts>py gimme-aws-creds
No OAuth Client ID in configuration.  Try running --config again.
No OAuth Authorization server in configuration.  Try running --config again.

**Comment by epierce** [comment]
Those configuration parameters are only used with the gimme-creds lambda service.  If you're not using that, you should save your Okta API key in the `OKTA_API_KEY` environment variable and set the `gimme_creds_server` configuration value to 'internal' to call the Okta APIs directly.

**Comment by arun-siv** [comment]
thanks please close it . I used appurl and its working fine 👍

**Comment by arun-siv** [comment]
I used 'appurl' when it asked for gimme_creds_server

**Comment by epierce** [comment]
Thanks for following up
