### ISSUE TITLE
Ability to define config variables as ENV variables

### ISSUE THREAD

**Issue by tluolamo** [Nike-Inc/gimme-aws-creds#88]
OKTA_USERNAME is already available as ENV variable. It would be helpful to allow each variable to be defined in ENV as well as in the config file.

**Comment by El-Dringo-Brannde** [comment]
@tluolamo Would this be for hypothetically using the rest of the values in the config file, and any variables in ENV would just overwrite those? That'd be interesting... say, hypothetically using two different profiles within the same company.

**Comment by tluolamo** [comment]
@El-Dringo-Brannde right. In the company I work for we already have 2 seperate AWS accounts enabled for Okta and we have dozens more that will likely be on-boarded for Okta integration in the near future. Anything to make these types of multi account scenarios easier would be great.

**Comment by Sector95** [comment]
Added to v1.1.5 release.
