### ISSUE TITLE
"CookieConflictError" when requesting renewing keys from Docker Container

### ISSUE THREAD

**Issue by migueleliasweb** [Nike-Inc/gimme-aws-creds#90]
Hi folks!

I'm getting this error when renewing keys.

```bash
$ gimme-aws-creds
Password for (ommited): 
Traceback (most recent call last):
  File "/usr/local/bin/gimme-aws-creds", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/opt/gimme-aws-creds/bin/gimme-aws-creds", line 17, in <module>
    GimmeAWSCreds().run()
  File "/opt/gimme-aws-creds/gimme_aws_creds/main.py", line 401, in run
    auth_result = okta.auth_session()
  File "/opt/gimme-aws-creds/gimme_aws_creds/okta.py", line 155, in auth_session
    return {"username": login_response['_embedded']['user']['profile']['login'], "session": response.cookies['sid'], "device_token": self._http_client.cookies['DT']}
  File "/usr/local/lib/python3.7/site-packages/requests-2.19.1-py3.7.egg/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/local/lib/python3.7/site-packages/requests-2.19.1-py3.7.egg/requests/cookies.py", line 394, in _find_no_duplicates
    raise CookieConflictError('There are multiple cookies with name, %r' % (name))
requests.cookies.CookieConflictError: There are multiple cookies with name, 'DT'
```

#### Given the stacktrace, I followed the rabbit down the hole.

The method `self._http_client.cookies['DT']` is failing to correctly return the value. As a simple test I tried accessing the cookie directly from the response and the expected value was actually there and without any duplicates.

So instead of:
```python3
return {
            "username": login_response['_embedded']['user']['profile']['login'],
            "session": response.cookies['sid'],
            "device_token": self._http_client.cookies['DT']
        }
```

I've changed to:
```python3
return {
            "username": login_response['_embedded']['user']['profile']['login'],
            "session": response.cookies['sid'],
            "device_token": response.cookies['DT']
        }
```

The only difference here is that instead of using the CookieJar from `self._http_client.cookies = jar` (gimme_aws_creds/okta.py:72) I've used the cookies references directly from the response.

I'm not sure why this error appears only when using the cookiejar from `self._http_client.cookies = jar` but I think it's safe to say using the response cookies is somewhat ok in this case. Tests are passing.

#### How to simulate the error?
Run the Docker container (as in the docs), punch the password and this error (sometimes) will arise. For me it only happens when you have already the device token set in your `~/.okta_aws_login_config`.

1. Run the container with `--entrypoint sh`
2. Run inside the container's shell:
```bash
$ pip install -r requirements_dev.txt
$ python setup.py develop
$ gimme-aws-creds
```

**Comment by fhenriquez** [comment]
I had a similar issue, which turned out to be a problem with my ~/.okta_aws_login_config. 

Removing the '/' at the end of the URL fixed the issue. Hope this helps. 

From:
`
okta_org_url = https://website.okta.com/ 
`
To:
`
okta_org_url = https://website.okta.com
`

**Comment by slmingol** [comment]
Confirming that the above was happening to me as well and sure enough, removal of the trailing slash, `/` on `okta_org_url` resolves this.
