### ISSUE TITLE
"Selection" breaks pipe to shell

### ISSUE THREAD

**Issue by kyeotic** [Nike-Inc/gimme-aws-creds#96]
At one point `gimme-aws-creds | sh` worked, but now because `Selection: 1` appears before the `export` statements, this pipe produces an error.

**Comment by linux2647** [comment]
What is it prompting for?  Okta selection?  AWS role selection?

**Comment by tyrsius** [comment]
Its not a prompt, its something gimme creds writes to STDOUT right before it prints the `exports ...` statements
